---
title: "This pipeline to generate sims for hood selection analysis (Augur)"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}

library(SingleCellExperiment)
library(BiocParallel)
library(geneBasisR)
library(splatter)
library(scran)
ncores = 6
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))

```

# Estimate parameters

```{r splatter-pars, message = FALSE}


sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/WT/mouse_embryo_E8.5.Rds"))
sce = sce[, sce$sample == 17]
sce = logNormCounts(sce)
sce = retain_informative_genes(sce , n = 4000)
counts(sce) = as.matrix(counts(sce))

params = splatEstimate( sce )


```

# Set parameter space

```{r assign-anno-grid, message = FALSE}


n_cells_total = c(5000)
n_batches = c(5)
group_prob = c(0.25 , 0.5 , 0.75)
de_prob = c(0, 0.05 , 0.25)
de_facLoc = c(1, 2)

anno = expand.grid(n_cells_total = n_cells_total , n_batches = n_batches,  group_prob = group_prob , de_prob = de_prob, de_facLoc = de_facLoc)
anno = unique(anno)


```

# Generate datsets

```{r gen-splatter-ds, message = FALSE}


get_sample_selection = function(samples , n_samples){
  samples = sort( sample(samples , n_samples) )
  return(samples)
}


sims_wo_batch = bplapply(1:nrow(anno) , function(i){
  n_cells_total = anno$n_cells_total[i]
  n_batches = anno$n_batches[i]
  group_prob = c(anno$group_prob[i] , 1 - anno$group_prob[i])
  de_prob = anno$de_prob[i]
  de_facLoc = anno$de_facLoc[i]
  n_cells_per_batch = rep(round(n_cells_total/n_batches) , 1 , n_batches)
    
  sim = splatSimulateGroups(params, group.prob = group_prob, de.prob = c(0,de_prob) , de.facLoc = de_facLoc , batchCells = n_cells_per_batch, verbose = FALSE,  out.prob = 0 , batch.rmEffect = T , de.downProb = 0)
  sim$sample = paste0(sim$Batch , "_" , sim$Group)
  
  # discard unnecessary fields
  sim = SingleCellExperiment(list(counts = counts(sim)), 
                           colData = colData(sim) , rowData = rowData(sim))
  # add logcounts
  sim = add_logcounts_simple(sim)
  return(sim)
} , BPPARAM = mcparam)
saveRDS(sims_wo_batch , file = paste0(root.dir , "data/processed/hood_selection/sims_wo_batch.Rds"))



# balanced batch
sims_w_batch = bplapply(1:nrow(anno) , function(i){
  n_cells_total = anno$n_cells_total[i]
  n_batches = anno$n_batches[i]
  group_prob = c(anno$group_prob[i] , 1 - anno$group_prob[i])
  de_prob = anno$de_prob[i]
  de_facLoc = anno$de_facLoc[i]
  n_cells_per_batch = rep(round(n_cells_total/n_batches) , 1 , n_batches)
    
  sim = splatSimulateGroups(params, group.prob = group_prob, de.prob = c(0,de_prob) , de.facLoc = de_facLoc , batchCells = n_cells_per_batch, verbose = FALSE,  out.prob = 0 , batch.rmEffect = F , de.downProb = 0)
  sim$sample = paste0(sim$Batch , "_" , sim$Group)
  
  # discard unnecessary fields
  sim = SingleCellExperiment(list(counts = counts(sim)), 
                           colData = colData(sim) , rowData = rowData(sim))
  # add logcounts
  sim = add_logcounts_simple(sim)
  return(sim)
} , BPPARAM = mcparam)
saveRDS(sims_w_batch , file = paste0(root.dir , "data/processed/hood_selection/sims_w_batch_balanced.Rds"))




# misbalanced batch
sims_w_batch = bplapply(1:nrow(anno) , function(i){
  n_cells_total = anno$n_cells_total[i]
  n_batches = anno$n_batches[i]
  group_prob = c(anno$group_prob[i] , 1 - anno$group_prob[i])
  de_prob = anno$de_prob[i]
  de_facLoc = anno$de_facLoc[i]
  n_cells_per_batch = rep(round(n_cells_total/n_batches) , 1 , n_batches)
    
  
  sim = splatSimulateGroups(params, group.prob = group_prob, de.prob = c(0,de_prob) , de.facLoc = de_facLoc , batchCells = n_cells_per_batch, verbose = FALSE,  out.prob = 0 , batch.rmEffect = F , de.downProb = 0)
  sim$sample = paste0(sim$Batch , "_" , sim$Group)
  
  # discard unnecessary fields
  sim = SingleCellExperiment(list(counts = counts(sim)), 
                           colData = colData(sim) , rowData = rowData(sim))
  
  # disbalance batches
  samples_query = get_sample_selection( unique(sim$sample[sim$Group == "Group1"]) , 3)
  samples_ref = get_sample_selection( unique(sim$sample[sim$Group == "Group2"]) , 3)
  sim = sim[ , sim$sample %in% c(samples_query , samples_ref)]
  
  # add logcounts
  sim = add_logcounts_simple(sim)
  return(sim)
} , BPPARAM = mcparam)
saveRDS(sims_w_batch , file = paste0(root.dir , "data/processed/hood_selection/sims_w_batch_misbalanced.Rds"))


```


# Session Info

```{r sessinf}
sessionInfo()
```
