---
title: "Select genes and simulate counts to immitate ground truth DE."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(miloR)
library(BiocParallel)
library(ggplot2)
library(ggpubr)
library(splatter)
library(scran)
library(edgeR)
library(dplyr)
library(scuttle)

ncores = 5
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)


root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
#root.dir = "/Users/alsu/Develop/hubmap_metaRef/"
source(paste0(root.dir , "am_hubmapMetaRef/functions/core_functions.R"))
source(paste0(root.dir , "am_hubmapMetaRef/functions/milo_functions.R"))


# load sce with embedding
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))

rowdata = as.data.frame(rowData(sce))
rowdata$n_cells_expressed = as.numeric( apply(counts(sce) , 1 , function(x) sum(x > 0)) )
rowdata$avg_expr = round( rowMeans(logcounts(sce)) , 1 )


```

# Select CTs to perturb

```{r sel-cts, message = FALSE}


celltypes = list("PGC" , "Blood progenitors 1" , "Blood progenitors 2" , "Erythroid1" , "Endothelium" , "Cardiomyocytes" , "Gut" ,  "Allantois" , "Pharyngeal mesoderm" , "Paraxial mesoderm" , "Mesenchyme" ,  c("Somitic mesoderm" , "Intermediate mesoderm" , "NMP") , c("Gut" , "Surface ectoderm") ,  "Forebrain/Midbrain/Hindbrain" , "Erythroid3" , c("Forebrain/Midbrain/Hindbrain" , "Spinal cord") , c("Forebrain/Midbrain/Hindbrain" , "Spinal cord" , "NMP") ,
                 c("Erythroid1" ,"Erythroid2" ,"Erythroid3") , c("Erythroid1" ,"Erythroid2" ,"Erythroid3" , "Blood progenitors 1" , "Blood progenitors 2" ) ,
                 c("Forebrain/Midbrain/Hindbrain" , "Spinal cord" , "NMP" , "Somitic mesoderm" , "Intermediate mesoderm") )


```


# Get genes that are not de in major CTs

```{r get-no-de-genes, message = FALSE}



get_no_de_genes = function(celltype , pval.thresh = 0.1 ){
  require(tibble)
  stat = tryCatch(
    {
      current.sce = sce[, sce$celltype == celltype]
      summed = summarizeAssayByGroup(counts(current.sce), colData(current.sce)[,c("sample","type")])
      y <- DGEList(assay(summed, "sum"), samples=colData(summed), lib.size = colSums(assay(summed , "sum")))
      y <- calcNormFactors(y)
      design <- model.matrix(~ factor(type), y$samples)
      y <- estimateDisp(y, design)
      fit <- glmQLFit(y, design, robust=TRUE)
      res <- glmQLFTest(fit, coef=ncol(design))
      out = topTags(res, n = Inf )
      out = as.data.frame(out)
      out = rownames_to_column(out , var = "ENSEMBL")
      out = out[out$PValue >= pval.thresh  , ]
      out$celltype = celltype
      out
    },
    error = function(dummy){
      return(NULL)
    }
  )
  return(stat)
}


no_de_genes = lapply(unique(sce$celltype) , function(celltype){
  print(celltype)
  out = get_no_de_genes(celltype , pval.thresh = 0.05) 
  return(out)
})
no_de_genes = do.call(rbind , no_de_genes)
n_celltypes = length(unique(no_de_genes$celltype))
no_de_genes = as.data.frame(no_de_genes %>% group_by(ENSEMBL) %>% dplyr::summarise(n_celltypes = n()))
no_de_genes = no_de_genes[no_de_genes$n_celltypes == n_celltypes , ]
no_de_genes = merge(no_de_genes , rowdata , all.x = T , all.y = F)




```

# Get candidate genes

```{r get-candidate-genes, message = FALSE}


K = 5
candidate_genes = lapply(unique(no_de_genes$avg_expr) , function(avg_expr){
  current.genes = no_de_genes$ENSEMBL[no_de_genes$avg_expr == avg_expr]
  current.genes = sample(current.genes , min(K , length(current.genes))) 
  return(current.genes)
})
candidate_genes = unlist(candidate_genes)

genes_2_simulate = data.frame(ENSEMBL = candidate_genes)
genes_2_simulate$range = sample(c(1,2), nrow(genes_2_simulate) , replace = T)
genes_2_simulate$frac_2_change = sample(c(1), nrow(genes_2_simulate) , replace = T)
genes_2_simulate = merge(genes_2_simulate , rowdata[, c("ENSEMBL" , "SYMBOL")] , all.x = T , all.y = F)

saveRDS(genes_2_simulate , file = paste0(root.dir , "data/processed/simulations/all_celltypes/simulated_genes.Rds"))



```

# Add simulated counts

```{r add-sim-counts, message = FALSE}



add_simulated_counts <- function(sce, celltypes = celltypes, gene, frac_cells_change, range){
  counts = counts(sce)
  current.counts = counts[gene, ]
  idx_2_change = which(sce$type == "chimera" & sce$celltype %in% celltypes)
  idx_2_change = sample(idx_2_change , round(length(idx_2_change)*frac_cells_change))
  current.counts[idx_2_change] = current.counts[idx_2_change] + floor(runif(length(idx_2_change), min=range[1], max=(range[2]+1)))
    
  counts[gene, ] = current.counts
  counts(sce) = counts
  return(sce)
}


sces = bplapply(celltypes , function(celltype){
  sce_simulated = sce
  for (i in 1:nrow(genes_2_simulate)){
    sce_simulated = add_simulated_counts(sce_simulated, celltypes = celltype, 
                             gene = genes_2_simulate$ENSEMBL[i], 
                             range = c(0 , genes_2_simulate$range[i]) , 
                             frac_cells_change = genes_2_simulate$frac_2_change[i])
  
  }
  sce_simulated = scuttle::logNormCounts(sce_simulated)
  return(sce_simulated)
} , BPPARAM = mcparam)
saveRDS(sces , file = paste0(root.dir , "data/processed/simulations/all_celltypes/sces_simulated.Rds"))



```


# Session Info

```{r sessinf}
sessionInfo()
```
