---
title: "This pipeline to generate sims for DA-DE analysis"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(BiocParallel)
library(geneBasisR)
library(splatter)
library(scran)
library(miloR)
library(miloDE)
library(dplyr)
library(tibble)
library(MouseGastrulationData)

ncores = 37
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))
source(paste0(root.dir , "am_hubmapMetaRef/functions/milo_functions.R"))


```

# Load data

```{r load-data, message = FALSE}


samples_e8.0 = AtlasSampleMetadata$sample[AtlasSampleMetadata$stage == "E8.0"]

sce <- lapply(samples_e8.0 , function(sample){
  out = EmbryoAtlasData(samples = sample)
  return(out)
})
sce = do.call(cbind , sce)




# load sce with embedding
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))
# will only work with blood cells
sce = sce[ , sce$celltype %in% c("Erythroid2" , "Erythroid3")]
rowdata = as.data.frame(rowData(sce))
rowdata$n_cells_expressed = as.numeric( apply(counts(sce) , 1 , function(x) sum(x > 0)) )
rowdata$avg_expr = round( rowMeans(logcounts(sce)) , 1 )


```

# Get genes for DE-DA

## Blood markers

```{r blood-spec-genes, message = FALSE}


markers = scran::findMarkers(sce , groups = sce$celltype)
markers = as.data.frame(markers[[1]])
markers = markers[markers$FDR < 0.01 & markers$summary.logFC < -0.5, c("p.value" , "FDR" , "summary.logFC")]
markers = tibble::rownames_to_column(markers , var = "ENSEMBL")
markers = merge(markers , rowdata , all.x = T , all.y = F)
markers = markers$ENSEMBL

```

## not DE genes

```{r not-de-genes, message = FALSE}


get_no_de_genes = function(celltype , pval.thresh = 0.1 ){
  require(tibble)
  current.sce = sce[, sce$celltype == celltype]
  summed = summarizeAssayByGroup(counts(current.sce), colData(current.sce)[,c("sample","type")])
  y <- DGEList(assay(summed, "sum"), samples=colData(summed), lib.size = colSums(assay(summed , "sum")))
  y <- calcNormFactors(y)
  design <- model.matrix(~ factor(type), y$samples)
  y <- estimateDisp(y, design)
  fit <- glmQLFit(y, design, robust=TRUE)
  res <- glmQLFTest(fit, coef=ncol(design))
  out = topTags(res, n = Inf )
  out = as.data.frame(out)
  out = rownames_to_column(out , var = "ENSEMBL")
  out = out[out$PValue >= pval.thresh  , ]
  out$celltype = celltype
  return(out)
}


no_de_genes = lapply(unique(sce$celltype) , function(celltype){
  out = get_no_de_genes(celltype , pval.thresh = 0.5) 
  return(out)
})
no_de_genes = do.call(rbind , no_de_genes)
no_de_genes = as.data.frame(no_de_genes %>% group_by(ENSEMBL) %>% dplyr::summarise(n_celltypes = n()))
no_de_genes = no_de_genes[no_de_genes$n_celltypes == length(unique(sce$celltype)) , ]
no_de_genes = merge(no_de_genes , rowdata , all.x = T , all.y = F)

K = 5
candidate_no_de_genes = lapply(unique(no_de_genes$avg_expr)[unique(no_de_genes$avg_expr) < 4] , function(avg_expr){
  current.genes = no_de_genes$ENSEMBL[no_de_genes$avg_expr == avg_expr]
  current.genes = sample(current.genes , min(K , length(current.genes))) 
  return(current.genes)
})
candidate_no_de_genes = unlist(candidate_no_de_genes)


```


## Get several gene combinations

```{r candidate-genes, message = FALSE}


anno = expand.grid(round = c(1:5) , n_markers = seq(0,length(markers) , 2))
anno$id = paste0(anno$round , "_" , anno$n_markers)
genes_2_simulate = lapply(1:nrow(anno) , function(i){
  out = data.frame(ENSEMBL = c(sample(markers , anno$n_markers[i]) , sample(candidate_no_de_genes , (length(markers)-anno$n_markers[i]))))
  out$gene_type = c(rep("marker" , anno$n_markers[i]) , rep("chimera_spec" , (length(markers)-anno$n_markers[i])))
  out$range = sample(c(1,2,3), nrow(out) , replace = T)
  out$frac_2_change = sample(c(1), nrow(out) , replace = T)
  out = merge(out , rowdata[, c("ENSEMBL" , "SYMBOL")] , all.x = T , all.y = F)
  return(out)
})
names(genes_2_simulate) = anno$id
saveRDS(genes_2_simulate , file = paste0(root.dir , "data/processed/da_de/simulations_chimera/blood/simulated_genes.Rds"))

```

# Add simulated counts

```{r add-sim-counts, message = FALSE}


hvgs = scran::getTopHVGs(sce[, sce$type == "wt"] , n = 1000)

add_batch_corrected_pca = function(sce, genes , reduced.dim_name = "pca.corrected" , batch = "sample" , d = 10, bpparam = NULL , correct = T){
  require(batchelor)
  set.seed(32)
  meta = as.data.frame(colData(sce))
  batchFactor = factor(meta[, colnames(meta) == batch])
  if (is.null(bpparam)){
    set.seed(32)
    mbpca = multiBatchPCA(sce[genes , ], batch = batchFactor, d = d)
  }
  else {
    set.seed(32)
    mbpca = multiBatchPCA(sce[genes , ], batch = batchFactor, d = d , BPPARAM = bpparam)
  }
  if (correct){
    out = do.call(reducedMNN, mbpca)
    joint.pca = out$corrected
  }
  else {
    joint.pca = do.call(rbind , mbpca)
  }
  joint.pca = joint.pca[order(rownames(joint.pca)) , ]
  sce = sce[, order(colnames(sce))]
  reducedDim(sce , reduced.dim_name) = joint.pca
  return(sce)
}


add_simulated_counts <- function(sce, gene, frac_cells_change, range){
  counts = counts(sce)
  current.counts = counts[gene, ]
  idx_2_change = which(sce$type == "chimera" & sce$celltype %in% c("Erythroid2"))
  idx_2_change = sample(idx_2_change , round(length(idx_2_change)*frac_cells_change))
  current.counts[idx_2_change] = current.counts[idx_2_change] + floor(runif(length(idx_2_change), min=range[1], max=(range[2]+1)))
  counts[gene, ] = current.counts
  counts(sce) = counts
  return(sce)
}


sces = bplapply(genes_2_simulate , function(current.genes_2_simulate){
  sce_simulated = sce
  for (i in 1:nrow(current.genes_2_simulate)){
    sce_simulated = add_simulated_counts(sce_simulated, 
                             gene = current.genes_2_simulate$ENSEMBL[i], 
                             range = c(0 , current.genes_2_simulate$range[i]) , 
                             frac_cells_change = current.genes_2_simulate$frac_2_change[i])
  
  }
  sce_simulated = scuttle::logNormCounts(sce_simulated)
  # add re-computed embedding
  sce_simulated = add_batch_corrected_pca(sce_simulated, genes = hvgs, reduced.dim_name = "pca.simulations" , batch = "sample" , d = 10, bpparam = NULL , correct = T)
    
  return(sce_simulated)
} , BPPARAM = mcparam)
names(sces) = anno$id
saveRDS(sces , file = paste0(root.dir , "data/processed/da_de/simulations_chimera/blood/sces_simulated.Rds"))



```



# Session Info

```{r sessinf}
sessionInfo()
```
