---
title: "Analysis to estimate how nhood sizes depend on [order-k]."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(miloDE)
library(miloR)
library(BiocParallel)
library(ggplot2)

ncores = 5
mcparam = MulticoreParam(workers = ncores)
register(mcparam)

set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
figures.dir = paste0(root.dir , "figures/optimal_coverage/k_2_hood_size/")

# load sce
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/WT/mouse_embryo_E8.5.Rds"))

# assign colours
cols_order = c("#3b7c70", "#ce9642")
names(cols_order) = c(1,2)


```


# Get and plot stat: diff k, order -> neighbourhood sizes

```{r get-stat, message = FALSE}



get_stat = function(sce , k , order){
  sce_milo = miloDE::assign_neighbourhoods(sce , reducedDim_name = "pca.corrected" , k = k , prop = 0.1 , order = order , filtering = F)
  nhoods_sce = nhoods(sce_milo)
  stat = data.frame(Nhood = 1:ncol(nhoods_sce) , hood_size = colSums(nhoods_sce))
  stat$order = order
  stat$k = k 
  return(stat)
}


anno_1 = data.frame(order = 1 , k = seq(50 , 500 , 50))
anno_2 = data.frame(order = 2 , k = seq(5 , 50 , 5))
anno = rbind(anno_1 , anno_2)


stat = lapply(1:nrow(anno) , function(i){
  print(i)
  out = get_stat(sce , k = anno$k[i] , order = anno$order[i])
  return(out)
})
stat = do.call(rbind , stat)

# plot
p = ggplot(stat , aes(x = factor(k) , y = hood_size , fill = factor(order))) +
  geom_boxplot(alpha = .9) +
  theme_bw() +
  scale_fill_manual(values = cols_order , name = "Order") +
  theme(axis.text.x = element_text(angle = 90)) + 
  facet_wrap(~order , scales = "free_x" , ncol = 2) +
  labs(x = "k" , y = "Neighbourhood size") +
  geom_hline(yintercept = 350 , "linetype" = "dashed") 
p
ggsave(filename = paste0(figures.dir , "k_2_hood_size.png"), plot = p, width = 7, height = 4)


```



# Session Info

```{r sessinf}
sessionInfo()
```
