---
title: "This pipeline to get joint final stat on DA-DE analysis"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}

library(SingleCellExperiment)
library(BiocParallel)
library(geneBasisR)
library(splatter)
library(scran)
library(miloR)
library(miloDE)
library(stringr)
library(dplyr)

ncores = 30
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))


# generated simulation data
sces = readRDS(file = paste0(root.dir , "data/processed/da_de/simulations_controlled_2/sims.Rds"))
simulated_genes = readRDS(file = paste0(root.dir , "data/processed/da_de/simulations_controlled_2/simulated_genes.Rds"))
stat_da = readRDS(file = paste0(root.dir , "data/processed/da_de/simulations_controlled_2/stat_da.Rds"))
stat_de = readRDS(file = paste0(root.dir , "data/processed/da_de/simulations_controlled_2/stat_de.Rds"))


```

# Get stat

## All genes combined

```{r stat-all-genes-comb, message = FALSE}


get_stat_per_sim_and_nhood_assignment = function(id_sim , id_nhood_assignment , reducedDim_name ){
  current.stat_da = stat_da[stat_da$id_sim == id_sim & stat_da$id_nhood_assignment == id_nhood_assignment & stat_da$reducedDim_name == reducedDim_name, ]
  
  out_da = as.data.frame(current.stat_da %>% group_by(id_sim , id_nhood_assignment , reducedDim_name) %>%
                                    dplyr::summarise(frac_hoods_DA_001 = mean(SpatialFDR <= 0.01 , na.rm = T) , 
                                                     frac_hoods_DA_005 = mean(SpatialFDR <= 0.01 , na.rm = T) , 
                                                     frac_hoods_DA_01 = mean(SpatialFDR <= 0.01 , na.rm = T)))


  current.stat_de = stat_de[stat_de$id_sim == id_sim & stat_de$id_nhood_assignment == id_nhood_assignment & stat_de$reducedDim_name == reducedDim_name, ]
  
  if (nrow(current.stat_de) > 0){
    current.stat_de = merge(current.stat_de , current.stat_da[, c("Nhood" , "SpatialFDR")] , by = c("Nhood") , all.x = T)
    
    # all DE
    out_de = as.data.frame(current.stat_de %>% group_by(id_sim , id_nhood_assignment , reducedDim_name , Gene , gene_type ) %>%
                                      dplyr::summarise(frac_hoods_DE_001 = mean(pval_corrected_across_nhoods <= 0.01 , na.rm = T) , 
                                                       frac_hoods_DE_005 = mean(pval_corrected_across_nhoods <= 0.05 , na.rm = T) , 
                                                       frac_hoods_DE_01 = mean(pval_corrected_across_nhoods <= 0.1 , na.rm = T) ))
    out_de = as.data.frame(out_de %>% group_by(id_sim , id_nhood_assignment , reducedDim_name , gene_type) %>%
                                      dplyr::summarise(frac_hoods_DE_001 = mean(frac_hoods_DE_001) , frac_hoods_DE_005 = mean(frac_hoods_DE_005) , frac_hoods_DE_01 = mean(frac_hoods_DE_01)))
    
    # DE in not DA
    out_de_not_da = as.data.frame(current.stat_de[current.stat_de$SpatialFDR > 0.1 , ] %>% group_by(id_sim , id_nhood_assignment , reducedDim_name , Gene , gene_type ) %>%
                                      dplyr::summarise(frac_hoods_DE_not_DA_001 = mean(pval_corrected_across_nhoods <= 0.01 , na.rm = T) , 
                                                       frac_hoods_DE_not_DA_005 = mean(pval_corrected_across_nhoods <= 0.05 , na.rm = T) , 
                                                       frac_hoods_DE_not_DA_01 = mean(pval_corrected_across_nhoods <= 0.1 , na.rm = T)
                                                       ))
    out_de_not_da = as.data.frame(out_de_not_da %>% group_by(id_sim , id_nhood_assignment , reducedDim_name , gene_type) %>%
                                      dplyr::summarise(frac_hoods_DE_not_DA_001 = mean(frac_hoods_DE_not_DA_001) , 
                                                       frac_hoods_DE_not_DA_005 = mean(frac_hoods_DE_not_DA_005) , 
                                                       frac_hoods_DE_not_DA_01 = mean(frac_hoods_DE_not_DA_01)))
    
    out_de = merge(out_de , out_de_not_da , by = c("id_sim" , "id_nhood_assignment" , "reducedDim_name" , "gene_type") , all.x = T , all.y = T)
  } else {
    out_de = data.frame(id_sim = rep(id_sim,2) , id_nhood_assignment = rep(id_nhood_assignment,2) ,
                                 reducedDim_name = rep(reducedDim_name , 2) , gene_type = c("marker" , "not_marker") , frac_hoods_DE_001 = c(NaN , NaN) , frac_hoods_DE_005 = c(NaN , NaN)  , frac_hoods_DE_01 = c(NaN , NaN)  , frac_hoods_DE_not_DA_001 = c(NaN , NaN)  , frac_hoods_DE_not_DA_005 = c(NaN , NaN)  , frac_hoods_DE_not_DA_01 = c(NaN , NaN) )
  }

  out = merge(out_da , out_de , by = c("id_sim" , "id_nhood_assignment" , "reducedDim_name"))
  out$reducedDim_name = as.character(reducedDim_name)
  out$id_sim = as.character(id_sim)
  out$id_nhood_assignment = as.character(id_nhood_assignment)
  
  return(out)
}


anno_sims = expand.grid(id_sim = unique(stat_da$id_sim), id_nhood_assignment = unique(stat_da$id_nhood_assignment) ,  reducedDim_name = unique(stat_da$reducedDim_name))

stat = bplapply(1:nrow(anno_sims) , function(i){
  out = get_stat_per_sim_and_nhood_assignment(as.character(anno_sims$id_sim[i]) , as.character(anno_sims$id_nhood_assignment[i]) , as.character(anno_sims$reducedDim_name[i]))
  return(out)
} , BPPARAM = mcparam)
stat = do.call(rbind , stat)
stat = merge(stat , unique(stat_da[, c("id_sim" , "effect_size" , "n_not_markers", "round_sim" , "order" , "k" , "seed" , "id_nhood_assignment" , "reducedDim_name")]) , by = c("id_sim" , "id_nhood_assignment" , "reducedDim_name") , all.x = T , all.y = F)

saveRDS(stat , file = paste0(root.dir , "data/processed/da_de/simulations_controlled_2/stat_combined_all_genes.Rds"))


```


# Session Info

```{r sessinf}
sessionInfo()
```
