---
title: "This pipeline to generate sims for DA-DE analysis"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}

library(SingleCellExperiment)
library(BiocParallel)
library(geneBasisR)
library(splatter)
library(scran)
ncores = 15
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))


```

# Estimate parameters

```{r splatter-pars, message = FALSE}


sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/WT/mouse_embryo_E8.5.Rds"))
sce = sce[, sce$sample == 17]
sce = logNormCounts(sce)
sce = retain_informative_genes(sce , n = 3000)
counts(sce) = as.matrix(counts(sce))

params = splatEstimate( sce )


```

# Set parameter space

```{r assign-anno-grid, message = FALSE}


n_cells_total = c(9000)
n_batches = c(3)
group_prob = c(0.5)
de_prob = c(0, 0.001 , 0.01 , 0.05 , 0.1 , 0.5)
de_facLoc = c(0.5 , 1 , 2 , 5 , 10)
batch = c(TRUE , FALSE)
round = c(1:3)

anno = expand.grid(n_cells_total = n_cells_total , n_batches = n_batches,  group_prob = group_prob , de_prob = de_prob, de_facLoc = de_facLoc , batch = batch , round = round)
anno = unique(anno)
anno$id = paste0(anno$batch , "_" , anno$de_prob , "_" , anno$de_facLoc , "_" , anno$round)


```

# Generate datsets

```{r gen-splatter-ds, message = FALSE}



add_batch_corrected_pca = function(sce, genes , reduced.dim_name = "pca.corrected" , batch = "sample" , d = 30, bpparam = NULL , correct = T){
  require(batchelor)
  set.seed(32)
  meta = as.data.frame(colData(sce))
  batchFactor = factor(meta[, colnames(meta) == batch])
  if (is.null(bpparam)){
    set.seed(32)
    mbpca = multiBatchPCA(sce[genes , ], batch = batchFactor, d = d)
  }
  else {
    set.seed(32)
    mbpca = multiBatchPCA(sce[genes , ], batch = batchFactor, d = d , BPPARAM = bpparam)
  }
  if (correct){
    out = do.call(reducedMNN, mbpca)
    joint.pca = out$corrected
  }
  else {
    joint.pca = do.call(rbind , mbpca)
  }
  joint.pca = joint.pca[order(rownames(joint.pca)) , ]
  sce = sce[, order(colnames(sce))]
  reducedDim(sce , reduced.dim_name) = joint.pca
  return(sce)
}


sims = bplapply(1:nrow(anno) , function(i){
  print(i)
  n_cells_total = anno$n_cells_total[i]
  n_batches = anno$n_batches[i]
  group_prob = c(anno$group_prob[i] , 1 - anno$group_prob[i])
  de_prob = anno$de_prob[i]
  de_facLoc = anno$de_facLoc[i]
  batch = anno$batch[i]
  round = anno$round[i]
  n_cells_per_batch = rep(round(n_cells_total/n_batches) , 1 , n_batches)
    
  sim = splatSimulateGroups(params, group.prob = group_prob, de.prob = c(0,de_prob) , de.facLoc = de_facLoc , batchCells = n_cells_per_batch, verbose = FALSE,  out.prob = 0 , batch.rmEffect = !batch , de.downProb = 0)
  sim$sample = paste0(sim$Batch , "_" , sim$Group)
  
  # discard unnecessary fields
  sim = SingleCellExperiment(list(counts = counts(sim)), 
                           colData = colData(sim) , rowData = rowData(sim))
  # add logcounts
  sim = scuttle::logNormCounts(sim)
  rowdata = as.data.frame(rowData(sim))	  
  # add MNN embedding (w and wo DE genes)
  sim = add_batch_corrected_pca(sim , genes = rowdata$Gene , reduced.dim_name = "pca.all" , d = 5)
  sim = add_batch_corrected_pca(sim , genes = rowdata$Gene[rowdata$DEFacGroup2 == 1] , reduced.dim_name = "pca.not_de" , d = 5)
  
  # add coldata
  sim$batch_effect = batch
  sim$n_batches = n_batches
  sim$de_prob = de_prob
  sim$de_facLoc = de_facLoc
  sim$round = round
  
  # delete logcounts
  sim_reduced = SingleCellExperiment(list(counts = as(counts(sim) , "dgCMatrix")) , 
                                     colData = colData(sim) , rowData = rowData(sim))
  colnames(sim_reduced) = colnames(sim)
  rownames(sim_reduced) = rownames(sim)
  
  reducedDim(sim_reduced , "pca.all") = reducedDim(sim , "pca.all")
  reducedDim(sim_reduced , "pca.not_de") = reducedDim(sim , "pca.not_de")
  
  return(sim_reduced)
} , BPPARAM = mcparam)
names(sims) = anno$id
saveRDS(sims , file = paste0(root.dir , "data/processed/da_de/simulations_splatter/sims.Rds"))


```


# Session Info

```{r sessinf}
sessionInfo()
```
