---
title: "This pipeline to extract mouse embryo (WT + WT-chimera)"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---


# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(MouseGastrulationData)
library(scran)
library(uwot)
library(BiocParallel)
library(zellkonverter)
ncores = 1
mcparam = MulticoreParam(workers = ncores)
register(mcparam)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))

set.seed(32)


```

# Load WT data (E8.5)

```{r load-wt-data, message = FALSE}


sce_ref = readRDS(paste0(root.dir , "data/sces/mouse_embryo/WT/mouse_embryo_E8.5.Rds"))
sce_ref$type = "wt"
sce_ref$tomato = FALSE

```

# Load chimera data (Tal1 one)

```{r load-chim-data, message = FALSE}


sce_chimera = WTChimeraData()

# delete doublets and stripped
sce_chimera = sce_chimera[, !sce_chimera$celltype.mapped %in% c("Doublet" , "Stripped")]

# select only stage E8.5
sce_chimera = sce_chimera[,sce_chimera$stage == "E8.5"]

# delete row for tomato
sce_chimera = sce_chimera[!rownames(sce_chimera) == "tomato-td" , ]

# add chimera_ prefix to avoid conclusion
colnames(sce_chimera) = paste0("chimera_" , colnames(sce_chimera) )
sce_chimera$cell = paste0("chimera_" ,sce_chimera$cell)
sce_chimera$sample = paste0("chimera_" , sce_chimera$sample )

sce_chimera$type = "chimera"



```

# Concatenate and add logcounts

```{r add-logcounts, message = FALSE}


# order rownames, check that dss are concatenable
sce_ref = sce_ref[order(rownames(sce_ref)) , ]
sce_chimera = sce_chimera[order(rownames(sce_chimera)) , ]
print(mean(rownames(sce_ref) == rownames(sce_chimera)))

# concatenate
sce = SingleCellExperiment(list(counts = cbind(counts(sce_ref) , counts(sce_chimera))))
# add metadata
sce$cell = c(sce_ref$cell , sce_chimera$cell)
sce$celltype = c(sce_ref$celltype , sce_chimera$celltype.mapped)
sce$sample = c(sce_ref$sample , sce_chimera$sample)
sce$type = c(sce_ref$type , sce_chimera$type)
sce$tomato = c(sce_ref$tomato , sce_chimera$tomato)

# add rowdata
rowData(sce) = rowData(sce_ref)

sce = add_logcounts(sce , batch = "sample")

saveRDS(sce , file = paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))


```


# Add adata

```{r add-adata, message = FALSE}


sce_reduced = SingleCellExperiment(list(counts = counts(sce)))
# add metadata
sce_reduced$cell = sce$cell
sce_reduced$celltype = sce$celltype
sce_reduced$sample = sce$sample
sce_reduced$type = sce$type
sce_reduced$tomato = sce$tomato

writeH5AD(sce_reduced , paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.h5ad") , compression = "gzip")



```

# Session Info

```{r sessinf}
sessionInfo()
```
