---
title: "Select genes and simulate counts to immitate ground truth DE."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(miloR)
library(BiocParallel)
library(ggplot2)
library(ggpubr)
library(splatter)
library(scran)
library(MetBrewer)
library(viridis)
library(slingshot)
ncores = 8
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)


root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
#root.dir = "/Users/alsu/Develop/hubmap_metaRef/"
source(paste0(root.dir , "am_hubmapMetaRef/functions/core_functions.R"))
source(paste0(root.dir , "am_hubmapMetaRef/functions/milo_functions.R"))


# load sce with embedding
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))
# subset for heart cells
sce = sce[, sce$celltype == "Erythroid3"]


rowdata = as.data.frame(rowData(sce))
rowdata$n_cells_expressed = as.numeric( apply(counts(sce) , 1 , function(x) sum(x > 0)) )
rowdata$avg_expr = round( rowMeans(logcounts(sce)) , 1 )


```

# Assign pseudotime

```{r cluster-braon-cells, message = FALSE}


set.seed(32)
slingshot_res <- slingPseudotime(slingshot(as.matrix(reducedDim(sce , "mnn_unsupervised_wt"))))
sce$pt = as.numeric(slingshot_res)

umaps = as.data.frame( scater::calculateUMAP(t(reducedDim(sce , "mnn_unsupervised_wt"))) )
reducedDim(sce , paste0("umap_" , "mnn_unsupervised_wt")) = umaps


meta = cbind(as.data.frame(colData(sce)) , as.data.frame(reducedDim(sce , "umap_mnn_unsupervised_wt")))

p = ggplot(meta , aes(x = V1 , y = V2 , col = pt)) +
  geom_point() +
  theme_bw() + 
  scale_color_viridis(discrete = F)
p


```

# Get cluster split

```{r cluster-split, message = FALSE}


pt_grid = sapply(seq(0,1,0.01) , function(i) return(as.numeric(quantile(sce$pt , i))))


cluster_splits = list(c(pt_grid[1] , pt_grid[3]) , 
                      c(pt_grid[49] , pt_grid[51]),
                      c(pt_grid[99] , pt_grid[101]),
                      c(pt_grid[1] , pt_grid[6]) , 
                      c(pt_grid[47] , pt_grid[53]),
                      c(pt_grid[95] , pt_grid[101]),
                      c(pt_grid[1] , pt_grid[11]) , 
                      c(pt_grid[45] , pt_grid[55]),
                      c(pt_grid[91] , pt_grid[101]),
                      c(pt_grid[1] , pt_grid[26]) , 
                      c(pt_grid[37] , pt_grid[63]),
                      c(pt_grid[75] , pt_grid[101])
                      )


```

# Get genes that are not de in major CTs

```{r get-no-de-genes, message = FALSE}



get_no_de_genes = function(sce , pval.thresh = 0.1 ){
  require(tibble)
  summed = summarizeAssayByGroup(counts(sce), colData(sce)[,c("sample","type")])
  y <- DGEList(assay(summed, "sum"), samples=colData(summed), lib.size = colSums(assay(summed , "sum")))
  y <- calcNormFactors(y)
  design <- model.matrix(~ factor(type), y$samples)
  y <- estimateDisp(y, design)
  fit <- glmQLFit(y, design, robust=TRUE)
  res <- glmQLFTest(fit, coef=ncol(design))
  out = topTags(res, n = Inf )
  out = as.data.frame(out)
  out = rownames_to_column(out , var = "ENSEMBL")
  out = out[out$PValue >= pval.thresh  , ]
  return(out)
}


no_de_genes = get_no_de_genes(sce , pval.thresh = 0.5)
no_de_genes = merge(no_de_genes , rowdata , all.x = T , all.y = F)


table(no_de_genes$avg_expr)



```

# Get candidate genes

```{r get-candidate-genes, message = FALSE}


K = 5
candidate_genes = lapply(unique(no_de_genes$avg_expr) , function(avg_expr){
  current.genes = no_de_genes$ENSEMBL[no_de_genes$avg_expr == avg_expr]
  current.genes = sample(current.genes , min(K , length(current.genes))) 
  return(current.genes)
})
candidate_genes = unlist(candidate_genes)

genes_2_simulate = data.frame(ENSEMBL = candidate_genes)
genes_2_simulate$range = sample(c(1,2,3), nrow(genes_2_simulate) , replace = T)
genes_2_simulate$frac_2_change = sample(c(1), nrow(genes_2_simulate) , replace = T)
genes_2_simulate = merge(genes_2_simulate , rowdata[, c("ENSEMBL" , "SYMBOL")] , all.x = T , all.y = F)

saveRDS(genes_2_simulate , file = paste0(root.dir , "data/processed/simulations/cardiomyocytes/simulated_genes.Rds"))



```

# Add simulated counts

```{r add-sim-counts, message = FALSE}


hvgs = scran::getTopHVGs(sce[, sce$type == "wt"] , n = 1000)

add_batch_corrected_pca = function(sce, genes , reduced.dim_name = "pca.corrected" , batch = "sample" , d = 10, bpparam = NULL , correct = T){
  require(batchelor)
  set.seed(32)
  meta = as.data.frame(colData(sce))
  batchFactor = factor(meta[, colnames(meta) == batch])
  if (is.null(bpparam)){
    set.seed(32)
    mbpca = multiBatchPCA(sce[genes , ], batch = batchFactor, d = d)
  }
  else {
    set.seed(32)
    mbpca = multiBatchPCA(sce[genes , ], batch = batchFactor, d = d , BPPARAM = bpparam)
  }
  if (correct){
    out = do.call(reducedMNN, mbpca)
    joint.pca = out$corrected
  }
  else {
    joint.pca = do.call(rbind , mbpca)
  }
  joint.pca = joint.pca[order(rownames(joint.pca)) , ]
  sce = sce[, order(colnames(sce))]
  reducedDim(sce , reduced.dim_name) = joint.pca
  return(sce)
}



add_simulated_counts <- function(sce, clusters = clusters, gene, frac_cells_change, range){
  counts = counts(sce)
  current.counts = counts[gene, ]
  idx_2_change = which(sce$type == "chimera" & sce$pt >= clusters[1] & sce$pt <= clusters[2])
  idx_2_change = sample(idx_2_change , round(length(idx_2_change)*frac_cells_change))
  current.counts[idx_2_change] = current.counts[idx_2_change] + floor(runif(length(idx_2_change), min=range[1], max=(range[2]+1)))
    
  counts[gene, ] = current.counts
  counts(sce) = counts
  return(sce)
}


sces = bplapply(cluster_splits , function(clusters){
  sce_simulated = sce
  for (i in 1:nrow(genes_2_simulate)){
    sce_simulated = add_simulated_counts(sce_simulated, clusters = clusters, 
                             gene = genes_2_simulate$ENSEMBL[i], 
                             range = c(0 , genes_2_simulate$range[i]) , 
                             frac_cells_change = genes_2_simulate$frac_2_change[i])
  
  }
  sce_simulated = scuttle::logNormCounts(sce_simulated)
  # add new embedding
  sce_simulated = add_batch_corrected_pca(sce_simulated , hvgs , reduced.dim_name = "pca.simulations")
  return(sce_simulated)
} , BPPARAM = mcparam)
saveRDS(sces , file = paste0(root.dir , "data/processed/simulations/cardiomyocytes/sces_simulated.Rds"))



```


# Session Info

```{r sessinf}
sessionInfo()
```
