---
title: "Run miloDE for different neighbourhood assignements of simulated data."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(batchelor)
library(stats)
library(BiocNeighbors)
library(tibble)
library(reshape2)
library(plyr)
library(dplyr)
library(scran)
library(stringr)
library(Seurat)
library(irlba)
library(igraph)
library(miloR)
library(ggplot2)
library(scater)
library(scran)
library(Matrix)
library(splatter)
library(BiocParallel)
library(BiocSingular)
library(miloDE)

ncores = 7
mcparam = MulticoreParam(workers = ncores)
register(mcparam)

set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"

simulated_genes = readRDS(file = paste0(root.dir , "data/processed/simulations/all_celltypes/simulated_genes.Rds"))
sces = readRDS(paste0(root.dir , "data/processed/simulations/all_celltypes/sces_simulated.Rds"))

celltypes = list("PGC" , "Blood progenitors 1" , "Blood progenitors 2" , "Erythroid1" , "Endothelium" , "Cardiomyocytes" , "Gut" ,  "Allantois" , "Pharyngeal mesoderm" , "Paraxial mesoderm" , "Mesenchyme" ,  c("Somitic mesoderm" , "Intermediate mesoderm" , "NMP") , c("Gut" , "Surface ectoderm") ,  "Forebrain/Midbrain/Hindbrain" , "Erythroid3" , c("Forebrain/Midbrain/Hindbrain" , "Spinal cord") , c("Forebrain/Midbrain/Hindbrain" , "Spinal cord" , "NMP") ,
                 c("Erythroid1" ,"Erythroid2" ,"Erythroid3") , c("Erythroid1" ,"Erythroid2" ,"Erythroid3" , "Blood progenitors 1" , "Blood progenitors 2" ) ,
                 c("Forebrain/Midbrain/Hindbrain" , "Spinal cord" , "NMP" , "Somitic mesoderm" , "Intermediate mesoderm") )



```

# Functions

```{r functions, message = FALSE}



get_bulk_de = function(sce , option = "all" , celltypes = "all" , genes){
  require(tibble)
  if (option == "some_celltypes"){
    sce = sce[, sce$celltype %in% celltypes]
  }
  summed = summarizeAssayByGroup(counts(sce), colData(sce)[,c("sample","type")])
  y <- DGEList(assay(summed, "sum"), samples=colData(summed), lib.size = colSums(assay(summed , "sum")))
  y <- calcNormFactors(y)
  design <- model.matrix(~ factor(type), y$samples)
  y <- estimateDisp(y, design)
  fit <- glmQLFit(y, design, robust=TRUE)
  res <- glmQLFTest(fit, coef=ncol(design))
  out = topTags(res, n = Inf )
  out = as.data.frame(out)
  out = rownames_to_column(out , var = "ENSEMBL")
  out = out[out$ENSEMBL %in% genes , ]
  return(out)
}



```

# Run bulkDE

```{r bulk-de, message = FALSE}



stat = bplapply(1:length(sces) , function(i){
  print(i)
  sce = sces[[i]]
  out_all = get_bulk_de(sce , genes = simulated_genes$ENSEMBL)
  out_all = out_all[, c("ENSEMBL" , "logFC" , "PValue" , "FDR")]
  colnames(out_all) = c("ENSEMBL" , "logFC_bulk_all" , "PValue_bulk_all" , "FDR_bulk_all")
  out_clusters = get_bulk_de(sce , option = "some_celltypes" , celltypes = celltypes[[i]] , genes = simulated_genes$ENSEMBL)
  out_clusters = out_clusters[, c("ENSEMBL" , "logFC" , "PValue" , "FDR")]
  colnames(out_clusters) = c("ENSEMBL" , "logFC_bulk_celltypes" , "PValue_bulk_celltypes" , "FDR_bulk_celltypes")
  out = merge(out_all , out_clusters)
  return(out)
} , BPPARAM = mcparam)
saveRDS(stat , file = paste0(root.dir , "data/processed/simulations/all_celltypes/bulk_de_stat.Rds"))





```

# Session Info

```{r sessinf}
sessionInfo()
```
