---
title: "This pipeline to get nhoods data from the simulations for DA-DE"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(BiocParallel)
library(geneBasisR)
library(splatter)
library(scran)
library(miloR)
library(miloDE)

ncores = 20
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))


sims = readRDS(file = paste0(root.dir , "data/processed/da_de/simulations_chimera/blood/sces_simulated.Rds"))

anno_1 = expand.grid(order = 1 , k = c(100,200) , seed = c(13,17,32))
anno_2 = expand.grid(order = 2 , k = c(15,25) , seed = c(13,17,32))
anno = rbind(anno_1 , anno_2)


```

# Get milo assignments

```{r get-milo-assign, message = FALSE}


stat = bplapply(sims , function(sim){
  stat_per_sim = lapply(1:nrow(anno) , function(i){
    
    set.seed(anno$seed[i])
    out = miloDE::assign_neighbourhoods(sim , reducedDim_name = "pca.simulations" , order = anno$order[i] , k = anno$k[i] , d = 5 , verbose = F , filtering = T)
    
    out = nhoods(out)
    return(out)
  })
  names(stat_per_sim) = paste0(anno$order , "_" , anno$k , "_seed_"  , anno$seed)
  return(stat_per_sim)
} , BPPARAM = mcparam)
names(stat) = names(sims)
saveRDS(stat , file = paste0(root.dir , "data/processed/da_de/simulations_chimera/blood/nhoods_sims.Rds"))



```



# Session Info

```{r sessinf}
sessionInfo()
```
