---
title: "Run miloDE for different neighbourhood assignements of simulated data."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(batchelor)
library(stats)
library(BiocNeighbors)
library(tibble)
library(reshape2)
library(plyr)
library(dplyr)
library(scran)
library(stringr)
library(Seurat)
library(irlba)
library(igraph)
library(miloR)
library(ggplot2)
library(scater)
library(scran)
library(Matrix)
library(splatter)
library(BiocParallel)
library(BiocSingular)
library(miloDE)

ncores = 6
mcparam = MulticoreParam(workers = ncores)
register(mcparam)

set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"

simulated_genes = readRDS(file = paste0(root.dir , "data/processed/simulations/cardiomyocytes/simulated_genes.Rds"))
sces = readRDS(paste0(root.dir , "data/processed/simulations/cardiomyocytes/sces_simulated.Rds"))


sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))
sce = sce[, sce$celltype == "Cardiomyocytes"]
set.seed(32)
slingshot_res <- slingPseudotime(slingshot(as.matrix(reducedDim(sce , "mnn_unsupervised_wt"))))
sce$pt = as.numeric(slingshot_res)
pt_grid = sapply(seq(0,1,0.01) , function(i) return(as.numeric(quantile(sce$pt , i))))

cluster_splits = list(c(pt_grid[1] , pt_grid[3]) , 
                      c(pt_grid[49] , pt_grid[51]),
                      c(pt_grid[99] , pt_grid[101]),
                      c(pt_grid[1] , pt_grid[6]) , 
                      c(pt_grid[47] , pt_grid[53]),
                      c(pt_grid[95] , pt_grid[101]),
                      c(pt_grid[1] , pt_grid[11]) , 
                      c(pt_grid[45] , pt_grid[55]),
                      c(pt_grid[91] , pt_grid[101]),
                      c(pt_grid[1] , pt_grid[26]) , 
                      c(pt_grid[37] , pt_grid[63]),
                      c(pt_grid[75] , pt_grid[101])
                      )

```


# Run bulkDE

## As discrete

```{r bulk-de, message = FALSE}




get_bulk_de = function(sce , clusters = "all" , genes){
  require(tibble)
  if (length(clusters) == 2){
    sce = sce[, sce$pt >= clusters[1] & sce$pt <= clusters[2]]
  }
  summed = summarizeAssayByGroup(counts(sce), colData(sce)[,c("sample","type")])
  y <- DGEList(assay(summed, "sum"), samples=colData(summed), lib.size = colSums(assay(summed , "sum")))
  y <- calcNormFactors(y)
  design <- model.matrix(~ factor(type), y$samples)
  y <- estimateDisp(y, design)
  fit <- glmQLFit(y, design, robust=TRUE)
  res <- glmQLFTest(fit, coef=ncol(design))
  out = topTags(res, n = Inf )
  out = as.data.frame(out)
  out = rownames_to_column(out , var = "ENSEMBL")
  out = out[out$ENSEMBL %in% genes , ]
  return(out)
}

stat = bplapply(1:length(sces) , function(i){
  print(i)
  sce = sces[[i]]
  out_all = get_bulk_de(sce , genes = simulated_genes$ENSEMBL)
  out_all = out_all[, c("ENSEMBL" , "logFC" , "PValue" , "FDR")]
  colnames(out_all) = c("ENSEMBL" , "logFC_bulk_all" , "PValue_bulk_all" , "FDR_bulk_all")
  out_clusters = get_bulk_de(sce , clusters = cluster_splits[[i]] , genes = simulated_genes$ENSEMBL)
  out_clusters = out_clusters[, c("ENSEMBL" , "logFC" , "PValue" , "FDR")]
  colnames(out_clusters) = c("ENSEMBL" , "logFC_bulk_clusters" , "PValue_bulk_clusters" , "FDR_bulk_clusters")
  out = merge(out_all , out_clusters)
  return(out)
},BPPARAM = mcparam)
saveRDS(stat , file = paste0(root.dir , "data/processed/simulations/cardiomyocytes/bulk_de_stat.Rds"))





```

## W pseudotime as a covariate

```{r bulk-de-w-pt, message = FALSE}


get_bulk_de = function(sce , genes){
  require(tibble)
  
  sce$pt = round(sce$pt)
  summed = summarizeAssayByGroup(counts(sce), colData(sce)[,c("sample","type","pt")])
  y <- DGEList(assay(summed, "sum"), samples=colData(summed), lib.size = colSums(assay(summed , "sum")))
  y <- calcNormFactors(y)
  design <- model.matrix(~ pt + factor(type), y$samples)
  y <- estimateDisp(y, design)
  fit <- glmQLFit(y, design, robust=TRUE)
  res <- glmQLFTest(fit, coef=ncol(design))
  out = topTags(res, n = Inf )
  out = as.data.frame(out)
  out = rownames_to_column(out , var = "ENSEMBL")
  out = out[out$ENSEMBL %in% genes , ]
  return(out)
}

stat = bplapply(1:length(sces) , function(i){
  print(i)
  sce = sces[[i]]
  out = get_bulk_de(sce , genes = simulated_genes$ENSEMBL)
  out = out[, c("ENSEMBL" , "logFC" , "PValue" , "FDR")]
  colnames(out) = c("ENSEMBL" , "logFC_w_pt" , "PValue_w_pt" , "FDR_w_pt")
  return(out)
},BPPARAM = mcparam)
saveRDS(stat , file = paste0(root.dir , "data/processed/simulations/cardiomyocytes/bulk_de_stat_w_pt.Rds"))


```

# Session Info

```{r sessinf}
sessionInfo()
```
