---
title: "Add MNN embedding to WT-chimera ds"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(BiocParallel)
library(scran)
library(batchelor)

ncores = 6
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))

# load sce 
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))

# load genes
genes_wt = read.csv(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/HVGs/wt.csv") , row.names = 1)
genes_all = read.csv(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/HVGs/all.csv") , row.names = 1)

genes = list(all = genes_all$HVG , wt = genes_wt$HVG)

```

# Define functions

Normal MNN is already in core-functions, need to add reference-projected PCA

```{r funcs, message = FALSE}


add_batch_corrected_supervised_pca = function(sce, genes , reduced.dim_name = "pca.corrected" , batch = "sample" , d = 30){
  require(batchelor)
  sce_ref = sce[, sce$type == "wt"]
  sce_query = sce[, !sce$type == "wt"]
  
  meta_ref = as.data.frame(colData(sce_ref))
  batchFactor_ref = factor(meta_ref[, colnames(meta_ref) == batch])
  
  full_pca = multiBatchPCA(sce_ref[genes,] , batch = batchFactor_ref , d = d, preserve.single = TRUE, assay.type = "logcounts")
  ref_pca <- full_pca[[1]]
  to_proj <- (as.matrix(logcounts(sce_query)[genes,]) - rowMeans(as.matrix(logcounts(sce_query)[genes,])))/sqrt(rowVars(as.matrix(logcounts(sce_query)[genes,])))

  map_pca <- t(to_proj) %*% metadata(full_pca)$rotation
  big_pca <- rbind(ref_pca, map_pca)
  # reorder
  big_pca = big_pca[order(rownames(big_pca)) , ]
  sce = sce[ , order(colnames(sce))]
  
  # correct
  meta = as.data.frame(colData(sce))
  batchFactor = factor(meta[, colnames(meta) == batch])
  
  out = reducedMNN(big_pca , batch = batchFactor )
  joint.pca = out$corrected
  reducedDim(sce , reduced.dim_name) = joint.pca
  return(sce)
}


```

# Run MNN

```{r run-mnn, message = FALSE}


anno = expand.grid(genes = c("wt" , "all") , embedding = c("supervised" , "unsupervised"))
anno$genes = as.character(anno$genes)
anno$embedding = as.character(anno$embedding)

for (i in 1:nrow(anno)){
  current.genes = genes[[which(names(genes) == anno$genes[i])]]
  if (anno$embedding[i] == "supervised"){
    sce = add_batch_corrected_supervised_pca(sce, genes = current.genes, reduced.dim_name = paste0("mnn_supervised_" , anno$genes[i]) , batch = "sample" , d = 30)
  } else {
    sce = add_batch_corrected_pca(sce, genes = current.genes, reduced.dim_name = paste0("mnn_unsupervised_" , anno$genes[i]) , batch = "sample" , d = 30, bpparam = mcparam , correct = T)
  }
}

saveRDS(sce , paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))  
  

```

# Session Info

```{r sessinf}
sessionInfo()
```
