---
title: "This pipeline to get DA statistic for DA-DE analysis"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(BiocParallel)
library(geneBasisR)
library(splatter)
library(scran)
library(miloR)
library(miloDE)
library(stringr)
library(dplyr)

ncores = 35
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))


sims = readRDS(file = paste0(root.dir , "data/processed/da_de/simulations_splatter/sims.Rds"))


anno_1 = expand.grid(order = 1 , k = c(100,200) , seed = c(13,17,32))
anno_2 = expand.grid(order = 2 , k = c(10,20) , seed = c(13,17,32))
anno = rbind(anno_1 , anno_2)
anno$id_nhood_assignment = paste0(anno$order , "_" , anno$k , "_" , anno$seed)


```

# Get milo DA stat

```{r milo-da-stat, message = FALSE}


get_milo_stat = function(sce_milo , reducedDim_name ){
  require(miloR)
  require(dplyr)
  
  sce_milo$sample <- as.factor( sce_milo$sample )
  sce_milo$type <- as.factor( sce_milo$type )
  
  sce_milo <- countCells(sce_milo, meta.data = as.data.frame(colData(sce_milo)), samples="sample")
  sce_design <- data.frame(colData(sce_milo))[,c("sample", "type")]
  sce_design <- distinct(sce_design)
  rownames(sce_design) <- sce_design$sample
  nhoodCounts(sce_milo) = as.matrix(nhoodCounts(sce_milo) , "dgCMatrix")
  
  out = testNhoods(sce_milo, design = ~ type , design.df = sce_design, fdr.weighting = "graph-overlap", reduced.dim = reducedDim_name)
  out$reducedDim_name = reducedDim_name
  out$n_hoods = nrow(out)
  out$n_cells_per_hood = colSums(nhoods(sce_milo))
  return(out)
}


stat = bplapply(1:length(sims) , function(j){
  sim = sims[[j]]
  stat_per_sim = lapply(1:nrow(anno) , function(i){
    set.seed(anno$seed[i])
    out_all = miloDE::assign_neighbourhoods(sim , reducedDim_name = "pca.all" , order = anno$order[i] , k = anno$k[i] , d = 5 , verbose = F , filtering = T)
    out_all = get_milo_stat(out_all , "pca.all")
    
    set.seed(anno$seed[i])
    out_hvgs = miloDE::assign_neighbourhoods(sim , reducedDim_name = "pca.hvgs" , order = anno$order[i] , k = anno$k[i] , d = 5 , verbose = F , filtering = T)
    out_hvgs = get_milo_stat(out_hvgs , "pca.hvgs")
    
    out = rbind(out_all , out_hvgs)
    out = cbind(out , anno[i , ])
    
    return(out)
  })
  stat_per_sim = do.call(rbind , stat_per_sim)
  
  id = names(sims)[j]
  stat_per_sim$id_sim = id
  id = stringr::str_split(id , "_")
  id = id[[1]]
  stat_per_sim$round_sim = as.numeric(id[1])
  stat_per_sim$n_hvgs = as.numeric(id[4])
  stat_per_sim$n_not_hvgs = as.numeric(id[9])
  return(stat_per_sim)
} , BPPARAM = mcparam)
stat = do.call(rbind , stat)
saveRDS(stat , file = paste0(root.dir , "data/processed/da_de/simulations_splatter/stat_da.Rds"))



```



# Session Info

```{r sessinf}
sessionInfo()
```
