---
title: "This pipeline to get DA statistic for DA-DE analysis"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}

library(SingleCellExperiment)
library(BiocParallel)
library(geneBasisR)
library(splatter)
library(scran)
library(miloR)
library(miloDE)
library(stringr)
library(dplyr)

ncores = 30
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))


sims = readRDS(file = paste0(root.dir , "data/processed/da_de/simulations_chimera/blood/sces_simulated.Rds"))
simulated_genes = readRDS(file = paste0(root.dir , "data/processed/da_de/simulations_chimera/blood/simulated_genes.Rds"))

anno_1 = expand.grid(order = 1 , k = c(75,150) , seed = c(13,17,32))
anno_2 = expand.grid(order = 2 , k = c(10,15) , seed = c(13,17,32))
anno = rbind(anno_1 , anno_2)


```

# Add stat for simulated genes

```{r sim-genes-stat, message = FALSE}


get_de_stat = function(sce , celltype = "Erythroid2", genes){
  require(tibble)
  require(edgeR)
  current.sce = sce[, sce$celltype == celltype]
  summed = summarizeAssayByGroup(counts(current.sce), colData(current.sce)[,c("sample","type")])
  y <- DGEList(assay(summed, "sum"), samples=colData(summed), lib.size = colSums(assay(summed , "sum")))
  y <- calcNormFactors(y)
  design <- model.matrix(~ factor(type), y$samples)
  y <- estimateDisp(y, design)
  fit <- glmQLFit(y, design, robust=TRUE)
  res <- glmQLFTest(fit, coef=ncol(design))
  out = topTags(res, n = Inf )
  out = as.data.frame(out)
  out = rownames_to_column(out , var = "ENSEMBL")
  out = out[out$ENSEMBL %in% genes , c("ENSEMBL" , "logFC" , "PValue" , "FDR")]
  colnames(out) = c("ENSEMBL" , "logFC_bulk" , "PValue_bulk" , "FDR_bulk")
  return(out)
}


simulated_genes = bplapply(1:length(simulated_genes) , function(i){
  current.genes = simulated_genes[[i]]
  de_stat = get_de_stat(sims[[i]] , genes = current.genes$ENSEMBL)
  current.genes = merge(current.genes , de_stat)
  return(current.genes)
} , BPPARAM = mcparam)





```

# Get milo DE stat

```{r milo-de-stat, message = FALSE}


get_de_selected_genes = function(sce_milo , genes){
 
  current.nhoods = nhoods(sce_milo)
  subset_nhoods = c(1:ncol(current.nhoods))
  
  de_stat = lapply(seq(length(subset_nhoods)) , function(i){
    hood_id = subset_nhoods[i]
    out = de_test_single_neighbourhood(sce_milo , nhoods_x = current.nhoods, hood_id = hood_id,
                                           sample_id = "sample", design = ~type, covariates = c("type"), contrasts = NULL,
                                           min_n_cells_per_sample = 1 ,
                                           min_count = 1 , run_separately = T)
    out = out[out$gene %in% genes , ]
    return(out)
  })
  
  # put together in SCE format
  de_stat_sce = SingleCellExperiment(list(logFC = matrix(NA, nrow = nrow(sce_milo), ncol = length(subset_nhoods)) ,
                                            pval = matrix(NA, nrow = nrow(sce_milo), ncol = length(subset_nhoods)) ,
                                            pval_corrected_across_genes = matrix(NA, nrow = nrow(sce_milo), ncol = length(subset_nhoods))))
  rownames(de_stat_sce) = rownames(sce_milo)
  for (i in seq(length(de_stat))){
    current.de_stat = de_stat[[i]]
    assay(de_stat_sce , "logFC")[current.de_stat$gene , i] = current.de_stat$logFC
    assay(de_stat_sce , "pval")[current.de_stat$gene , i] = current.de_stat$pval
    assay(de_stat_sce , "pval_corrected_across_genes")[current.de_stat$gene , i] = current.de_stat$pval_corrected_across_genes
  }

  # add coldata on nhoods
  meta_nhoods = lapply(seq(length(de_stat)) , function(i){
    current.de_stat = de_stat[[i]]
    current.meta = unique(current.de_stat[, c("Nhood" , "Nhood_center" , "test_performed" )])
    return(current.meta)
  })
  meta_nhoods = do.call(rbind , meta_nhoods)
  colData(de_stat_sce) = DataFrame(meta_nhoods)
  colnames(de_stat_sce) = meta_nhoods$Nhood
  
  # select genes w at least one test
  idx = which( rowMeans(is.na(assay(de_stat_sce , "pval"))) < 1)
  de_stat_sce = de_stat_sce[idx , ]
  
  # pval correction
  pval_corrected = lapply(rownames(de_stat_sce) , function(gene){
    pvals = assay(de_stat_sce , "pval")[gene , ]
    out = miloDE::spatial_pval_adjustment(nhoods_x = as.matrix(current.nhoods[,subset_nhoods]) , pvalues = pvals)
    return(out)
  })

  # add the assay into final de-stat
  assay_pval_corrected_across_nhoods = do.call(rbind , pval_corrected)
  rownames(assay_pval_corrected_across_nhoods) = rownames(de_stat_sce)
  colnames(assay_pval_corrected_across_nhoods) = colnames(de_stat_sce)
  assay(de_stat_sce , "pval_corrected_across_nhoods") = assay_pval_corrected_across_nhoods
  
  # convert to data.frame
  de_stat = convert_de_stat(de_stat_sce)
  return(de_stat)
}


stat = bplapply(1:length(sims) , function(j){
  sim = sims[[j]]
  current.genes = simulated_genes[[j]]
  stat_per_sim = lapply(1:nrow(anno) , function(i){
    set.seed(anno$seed[i])
    out = miloDE::assign_neighbourhoods(sim , reducedDim_name = "pca.simulations" , order = anno$order[i] , k = anno$k[i] , d = 10 , verbose = F , filtering = T)
    out = get_de_selected_genes(out , genes = current.genes$ENSEMBL)
    colnames(out)[colnames(out) == "gene"] = "ENSEMBL"
    out = merge(out , current.genes , all.x = T)
    
    out = cbind(out , anno[i , ])
    return(out)
  })
  stat_per_sim = do.call(rbind , stat_per_sim)
  
  id = names(sims)[j]
  stat_per_sim$id_sim = id
  id = stringr::str_split(id , "_")
  id = id[[1]]
  stat_per_sim$round_sim = as.numeric(id[1])
  stat_per_sim$n_markers = as.numeric(id[2])
  
  return(stat_per_sim)
} , BPPARAM = mcparam)
stat = do.call(rbind , stat)
saveRDS(stat , file = paste0(root.dir , "data/processed/da_de/simulations_chimera/blood/stat_de.Rds"))



```


# Session Info

```{r sessinf}
sessionInfo()
```
