---
title: "Assign neighbourhoods and miloDE for different embeddings."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(miloDE)
library(miloR)
library(BiocParallel)
library(ggplot2)
library(ggpubr)
library(geneBasisR)
library(MouseGastrulationData)
library(scran)
library(MetBrewer)

ncores = 1
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"

# load sce 
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))


```

# Assign neighbourhoods

```{r assign-nhoods, message = FALSE}


anno_1 = expand.grid(reduced_dim = reducedDimNames(sce) , order = 1 , k = c(100,200) , round = c(1:3))
anno_2 = expand.grid(reduced_dim = reducedDimNames(sce) , order = 2 , k = c(10,20) , round = c(1:3))
anno = rbind(anno_1 , anno_2)
anno$id = paste0(anno$reduced_dim , "_" , anno$order , "_" , anno$k , "_" , anno$round)

# add seeds
anno$seed = 13
anno$seed[anno$round == 2] = 32
anno$seed[anno$round == 3] = 98

sce_milo = lapply(1:nrow(anno) , function(i){
 set.seed(anno$seed[i])
 current.sce = miloDE::assign_neighbourhoods(sce , reducedDim_name = as.character(anno$reduced_dim[i]) , k = anno$k[i], prop = 0.1 , order = anno$order[i], filtering = T)
 return(nhoods(current.sce))
})
names(sce_milo) = anno$id
saveRDS(sce_milo , file = paste0(root.dir , "data/processed/embedding_analysis_updated/sce_milo_nhoods.Rds"))




```

# Session Info

```{r sessinf}
sessionInfo()
```
