---
title: "Assign neighbourhoods and miloDE for different embeddings."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(miloDE)
library(miloR)
library(BiocParallel)
library(ggplot2)
library(ggpubr)
library(geneBasisR)
library(MouseGastrulationData)
library(scran)
library(MetBrewer)

ncores = 15
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"

# load sce 
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))

```

# Get HVGs

Either only atlas (aka reference) or union of atlas and chimera

```{r get-hvgs, message = FALSE}


get_hvgs = function(sce , type , n = 3000){
  require(scran)
  current.sce = sce[, sce$type == type]
  hvgs = getTopHVGs(current.sce , n = n)
  return(hvgs)
}

hvgs_wt = get_hvgs(sce , "wt")
hvgs_chimera = get_hvgs(sce , "chimera")
hvgs_union = unique(c(hvgs_wt , hvgs_chimera))

hvgs_wt = as.data.frame(hvgs_wt)
colnames(hvgs_wt) = "HVG"
write.csv(hvgs_wt , paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/HVGs/wt.csv"))

hvgs_union = as.data.frame(hvgs_union)
colnames(hvgs_union) = "HVG"
write.csv(hvgs_union , paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/HVGs/all.csv"))



```


# Session Info

```{r sessinf}
sessionInfo()
```
