---
title: "This pipeline to test different how homogeneity varies between miloDE and bulk"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(miloDE)
library(miloR)
library(BiocParallel)
library(ggplot2)
library(ggpubr)
library(geneBasisR)
library(MouseGastrulationData)
library(scran)
library(MetBrewer)

ncores = 7
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)


root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
figures.dir = paste0(root.dir , "figures/homogeneity_comparison/")


# load sce with embedding
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))
# subset
sce = sce[, sce$type == "wt" & sce$celltype == "Forebrain/Midbrain/Hindbrain"]

# add pca to sce
sce = add_batch_corrected_pca(sce, genes = NULL, reduced.dim_name = "pca.brain" , batch = "sample" , d = 5, bpparam = NULL , correct = T , add_umaps = T)
  

# select good genes
rowdata = as.data.frame(rowData(sce))
rownames(sce) = rowdata$SYMBOL
genes = c("En1" , "Fgf8" , "Msx3" , "Wnt1" , "Efna2" , "Fgf17" , "Otx2" , "Shh" , "Foxa2" , "Lmo1")
sce = sce[genes, ]




```

# Assign neighbourhoods

```{r assign-hoods, message = FALSE}


anno_1 = expand.grid(order = 1 , k = c(25 , 50) , seed = c(13))
anno_2 = expand.grid(order = 2 , k = c(10, 15) , seed = c(13))
anno = rbind(anno_1 , anno_2)
anno$id_nhood_assignment = paste0(anno$order , "_" , anno$k , "_" , anno$seed)


sce_milo = lapply(1:nrow(anno), function(i){
  
  out = miloDE::assign_neighbourhoods(sce , reducedDim_name = "pca.brain" , order = anno$order[i] , k = anno$k[i] , d = 5 , verbose = F , filtering = T)
  return(out)
})
names(sce_milo) = anno$id 



```

# Calc mean and sd

## Bulk - all cells


```{r calc-stat-bulk, message = FALSE}


stat_all = data.frame(gene = rownames(sce) , mean_all = rowMeans(logcounts(sce), na.rm=TRUE) , sd_all = rowSds(logcounts(sce), na.rm=TRUE))


```


## For each nhood assignment


```{r stat-heterogeneity-hoods, message = FALSE}



get_mean_sd_distr_per_hood = function(idx_milo , gene){
  df = data.frame(cell = colnames(sce) , 
                            counts = as.numeric(logcounts(sce[gene , ])))
  nhoods_sce = nhoods(sce_milo[[idx_milo]])
  
  stat = bplapply(1:ncol(nhoods_sce) , function(i){
    idx = which(nhoods_sce[,i] == 1 )
    current.df = df[df$cell %in% rownames(nhoods_sce)[idx],]
    current.stat = data.frame(mean_hood = mean(current.df$counts) , sd_hood = sd(current.df$counts))
    current.stat$Nhood = i
    return(current.stat)
  }, BPPARAM = mcparam)
  stat = do.call(rbind , stat)
  id = names(sce_milo)[idx_milo]
  stat$id = id
  stat$gene = gene
  return(stat)
}



anno_hoods = expand.grid(gene = rownames(sce) , idx_milo = c(1:length(sce_milo)))
stat_nhoods = lapply(1:nrow(anno_hoods) , function(i){
  out = get_mean_sd_distr_per_hood(anno_hoods$idx_milo[i] , as.character(anno_hoods$gene[i]))
  return(out)
})
stat_nhoods = do.call(rbind , stat_nhoods)

saveRDS(stat_nhoods , paste0(root.dir , "data/temp/homogeneity_comparison_stat.Rds"))



```


# Plot

```{r plot-sd-boxplot, message = FALSE}


plots = lapply(genes , function(gene){
  current.stat_nhoods = stat_nhoods[stat_nhoods$gene == gene , ]
  current.stat_all = stat_all[stat_all$gene == gene , ]
  p = ggplot() +
    geom_point(data = current.stat_nhoods , aes(x = mean_hood , y = sd_hood , col = id) , size = .5) +
    geom_point(data = current.stat_all , aes(x = mean_all , y = sd_all),  col = "black" , size = 2) +
    theme_bw() + 
    ggtitle(gene) 
  return(p)
})
p = ggarrange(plotlist = plots , common.legend = T)
p
ggsave(filename = paste0(figures.dir, "stat", ".png"), plot = p, width = 8, height = 6)


```


# DE-stat

## load DE stat for select genes


```{r boxplot-distr-milo-de, message = FALSE}



de_stat = readRDS( paste0(root.dir , "data/processed/embedding_analysis_updated/milo_de_chimera_genes.Rds") )
rowdata = as.data.frame(rowData(sce))
colnames(de_stat)[colnames(de_stat) == "gene"] = "ENSEMBL"
de_stat = merge(de_stat , rowdata , all.x = T , all.y = F)
de_stat = de_stat[de_stat$SYMBOL %in% chimera_speicific_stat$SYMBOL , ]
de_stat$SYMBOL = factor(de_stat$SYMBOL , levels = chimera_speicific_genes)

# add number of cells stat
df = lapply(unique(de_stat$id) , function(id){
  nhoods_sce = sce_milo_nhoods[[which(names(sce_milo_nhoods) == id)]]
  out = data.frame(Nhood_center = colnames(nhoods_sce) , n_cells = colSums(nhoods_sce))
  out$id = id
  return(out)
})
df = do.call(rbind , df)

de_stat = merge(de_stat , df , by= c("Nhood_center" , "id") , all.x = T)
de_stat = merge(de_stat , de_stat_per_gene[, c("ENSEMBL" , "median_logFC" , "mean_logFC" , "logFC_all")] , all.x = T , all.y = F)


```

## Boxplot distr - logFC and n-hoods-sig

```{r boxplot-distr-milo-de, message = FALSE}


names(embedding_cols) = embeddings

plots = lapply(chimera_speicific_stat$SYMBOL, function(gene){
  gene = genes[i]
  p = ggplot(de_stat[de_stat$SYMBOL == gene , ], aes(x = SYMBOL , y = logFC , fill = embedding)) + 
    geom_boxplot(alpha = .8 , outlier.size = .25) + 
    theme_bw() + 
    theme(axis.text.x = element_blank()) + 
    scale_fill_manual(values = embedding_cols) +
    labs(x = "" ) + 
    theme(legend.position = "none") + 
    ylim(c(0 , lims[i])) +
    geom_hline(yintercept = de_stat_per_gene$median_logFC[de_stat_per_gene$SYMBOL == gene] , "color" = "black" , "linetype" = "dashed") + 
    ggtitle(gene)
  return(p)
})
p = ggarrange(plotlist = plots , ncol = 3)
p
ggsave(filename = paste0(figures.dir, "milo_de/logFC_distr", ".png"), plot = p, width = 7, height = 3)



# check p-value stat
unq.embeddings = as.character(unique(de_stat$embedding))
unq.embeddings_grid = expand.grid(embedding_1 = unq.embeddings , 
                                  embedding_2 = unq.embeddings , gene = genes_chimera_specific )
unq.embeddings_grid = unq.embeddings_grid[!unq.embeddings_grid$embedding_1 ==
                                            unq.embeddings_grid$embedding_2 , ]  

pval_stat = sapply(1:nrow(unq.embeddings_grid) , function(i){
  current.gene = unq.embeddings_grid$gene[i]
  x = de_stat$logFC[ de_stat$SYMBOL == current.gene & de_stat$embedding == unq.embeddings_grid$embedding_1[i]]
  y = de_stat$logFC[de_stat$SYMBOL == current.gene & de_stat$embedding == unq.embeddings_grid$embedding_2[i]]
    
  current.test = t.test(x , y )  
  return(current.test$p.value)
})
unq.embeddings_grid$pval = pval_stat

unq.embeddings_grid$embedding_1 = factor(unq.embeddings_grid$embedding_1 , levels = embeddings)
unq.embeddings_grid$embedding_2 = factor(unq.embeddings_grid$embedding_2 , levels = embeddings)


# test for diff genes what is there p-value distr
unq.embeddings_grid$test = unq.embeddings_grid$pval < 0.05
p = ggplot(unq.embeddings_grid , aes(x = embedding_1 , y = embedding_2 , fill = test )) +
  geom_tile() +
  facet_wrap(~gene) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p




```

## Combined stat

```{r boxplot-distr-milo-de, message = FALSE}


de_stat_combined = as.data.frame(de_stat %>% group_by(SYMBOL , id , reduced_dim_method , reduced_dim_type , reduced_dim_genes , reduced_dim , order , k , round) %>% dplyr::summarise(logFC = median(logFC , na.rm = T) , mean_logFC = mean(mean_logFC , na.rm = T), median_logFC = mean(median_logFC , na.rm = T),  logFC_all = mean(logFC_all , na.rm = T), frac_hoods_sig_01 = mean(pval < 0.1 , na.rm = T) , frac_hoods_sig_005 = mean(pval < 0.05 , na.rm = T) , frac_hoods_sig_001 = mean(pval < 0.01 , na.rm = T) , frac_hoods_sig_0001 = mean(pval < 0.005 , na.rm = T)  , frac_hoods_sig_0005 = mean(pval < 0.001 , na.rm = T) , frac_hoods_sig_00001 = mean(pval < 0.0001 , na.rm = T) ))

de_stat_combined = de_stat_combined[de_stat_combined$reduced_dim %in% anno$reducedDim.name , ]
de_stat_combined$reduced_dim = factor(de_stat_combined$reduced_dim , levels = anno$reducedDim.name)
de_stat_combined$reduced_dim_type_genes = paste0(de_stat_combined$reduced_dim_type , "_" , de_stat_combined$reduced_dim_genes)
de_stat_combined$reduced_dim_type_genes = factor(de_stat_combined$reduced_dim_type_genes , levels = c("unsupervised_wt" , "unsupervised_all" , "supervised_wt" , "supervised_all"))



plots = lapply(unique(de_stat_combined$SYMBOL) , function(gene){
  p = ggplot(de_stat_combined[de_stat_combined$SYMBOL == gene, ] , aes(x = reduced_dim_method , y = frac_hoods_sig_001 , fill = reduced_dim_type_genes)) +
    geom_boxplot() +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    ggtitle(gene) + 
    scale_fill_manual(values = cols, name = "Embedding") + 
    labs(x = "" , y = "") + 
    ylim(c(0.65 , 1))
  return(p)
})
p = ggarrange(plotlist = plots , common.legend = T , ncol = length(chimera_speicific_genes) , nrow = 1)
p
ggsave(filename = paste0(figures.dir, "frac_sig_distr", ".png"), plot = p, width = 12, height = 3)




plots = lapply(unique(de_stat_combined$SYMBOL) , function(gene){
  p = ggplot(de_stat_combined[de_stat_combined$SYMBOL == gene, ] , aes(x = reduced_dim_method , y = abs(logFC) , fill = reduced_dim_type_genes)) +
    geom_boxplot() +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
    ggtitle(gene) + 
    scale_fill_manual(values = cols , name = "Embedding") + 
    labs(x = "" , y = "") +
    geom_hline(yintercept = abs(unique(de_stat_combined$logFC_all[de_stat_combined$SYMBOL == gene])) , "color" = "black" , "linetype" = "dashed") 
  return(p)
})
p = ggarrange(plotlist = plots , common.legend = T , ncol = length(chimera_speicific_genes) , nrow = 1)
p
ggsave(filename = paste0(figures.dir, "logFC_distr", ".png"), plot = p, width = 12, height = 3)


```

# Session Info

```{r sessinf}
sessionInfo()
```
