---
title: "This pipeline to select genes and simulate perturbed counts for the order analysis."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(miloR)
library(BiocParallel)
library(ggplot2)
library(ggpubr)
library(geneBasisR)
library(splatter)
library(scran)
library(MetBrewer)
library(viridis)
library(stringr)
library(tibble)
library(dplyr)
library(reshape2)
library(scuttle)

ncores = 5
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"

# load sce with embedding
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera/mouse_embryo_chimera_tal.Rds"))
# subselect only for Tal1+
sce = sce[, sce$tal1 == 1]

# update ct names
sce$celltype = sapply(sce$celltype , function(x) str_replace_all(x , "/" , "_"))
sce$celltype = sapply(sce$celltype , function(x) str_replace_all(x , " " , "_"))
sce$sub_celltype = sapply(sce$sub_celltype , function(x) str_replace_all(x , "/" , "_"))
sce$sub_celltype = sapply(sce$sub_celltype , function(x) str_replace_all(x , " " , "_"))
#sce$celltype = sce$sub_celltype

# get rowdata
rowdata = as.data.frame(rowData(sce))
rowdata$n_cells_expressed = as.numeric( apply(counts(sce) , 1 , function(x) sum(x > 0)) )
rowdata$avg_expr = round( rowMeans(logcounts(sce)) , 1 )

# select cts - at s 20 in each type - to exclude highly rare CTs
tab = table(sce$celltype , sce$type)
cts = sapply(rownames(tab) , function(i) ifelse(min(tab[i,]) >= 20  , T , F))
cts = names(cts)[cts == T]

for (ct in cts){
  rowdata$var = round( rowMeans(logcounts(sce[, sce$celltype == ct])) , 1 )
  colnames(rowdata)[colnames(rowdata) == "var"] = paste0("avg_expr_" , ct)
}


```


# Get genes that are not de

```{r get-no-de-genes, message = FALSE}



get_no_de_genes = function(celltype , pval.thresh = 0.1 ){
  require(tibble)
  current.sce = sce[, sce$celltype == celltype]
  summed = summarizeAssayByGroup(counts(current.sce), colData(current.sce)[,c("sample","type")])
  y <- DGEList(assay(summed, "sum"), samples=colData(summed), lib.size = colSums(assay(summed , "sum")))
  y <- calcNormFactors(y)
  design <- model.matrix(~ factor(type), y$samples)
  y <- estimateDisp(y, design)
  fit <- glmQLFit(y, design, robust=TRUE)
  res <- glmQLFTest(fit, coef=ncol(design))
  out = topTags(res, n = Inf )
  out = as.data.frame(out)
  out = rownames_to_column(out , var = "ENSEMBL")
  #out = merge(out , rowdata)
  out = out[out$PValue >= pval.thresh  , ]
  #out = out[out$avg_expr < 1 & out$n_cells_expressed < 10000, ]
  out$celltype = celltype
  return(out)
}


no_de_genes = bplapply(cts , function(ct){
  print(ct)
  out = get_no_de_genes(ct) 
  return(out)
} , BPPARAM = mcparam)
no_de_genes = do.call(rbind , no_de_genes)
no_de_genes = as.data.frame(no_de_genes %>% group_by(ENSEMBL) %>% dplyr::summarise(n_cts = n()))
no_de_genes = no_de_genes[no_de_genes$n_cts == length(cts) , ]
no_de_genes = merge(no_de_genes , rowdata , all.x = T , all.y = F)


```

# Get candidate genes of different average expression ranges

```{r get-candidate-genes, message = FALSE}



get_candidate_genes = function(genes , avg_expr.grid, ct , n_genes = 10){
  candidate_genes = lapply(avg_expr.grid , function(avg_expr){
    current.rowdata = rowdata[rowdata$ENSEMBL %in% genes , ]
    var = paste0("avg_expr_" , ct)
    current.genes = sample(current.rowdata$ENSEMBL[current.rowdata[, var] == avg_expr] , min(n_genes, length(current.rowdata$ENSEMBL[current.rowdata[, var] == avg_expr])))
    current.genes = current.rowdata[current.rowdata$ENSEMBL %in% current.genes , c("ENSEMBL" , "SYMBOL")]
    current.genes$avg_expr = avg_expr
    return(current.genes)
  })
  candidate_genes = do.call(rbind , candidate_genes)
  candidate_genes$celltype = ct
  return(candidate_genes)
}
 

avg_expr.grid = c(0 , 0.1 , 0.2 , 0.3 , 0.4 , 0.5)


genes_2_simulate = lapply(cts, function(ct){
  print(ct)
  out = get_candidate_genes(no_de_genes$ENSEMBL , avg_expr.grid = avg_expr.grid , ct , n_genes = 10)
  return(out)
})
genes_2_simulate = do.call(rbind, genes_2_simulate)

# add range and frac to be permuted
genes_2_simulate$range = sample(c(1,2), nrow(genes_2_simulate) , replace = T)
genes_2_simulate$frac_2_change = sample(c(1), nrow(genes_2_simulate) , replace = T)
saveRDS(genes_2_simulate , file = paste0(root.dir , "data/processed/order_analysis_full_ds/simulated_genes_full_ds.Rds"))


# add entries for dupped genes
tab = sort(table(genes_2_simulate$ENSEMBL))
genes_dupped = names(tab)[tab > 1]
sce_2_add = lapply(genes_dupped , function(gene){
  print(gene)
  idx = which(genes_2_simulate$ENSEMBL == gene)
  current.cts = genes_2_simulate$celltype[idx]
  current.sce = sce[gene , ]
  out = lapply(current.cts , function(ct){
    return(current.sce)
  })
  out = do.call(rbind , out)
  rowData(out)[,1] = paste0(gene , "_" , current.cts)
  rownames(out) = paste0(gene , "_" , current.cts)
  return(out)
})
sce_2_add = do.call(rbind , sce_2_add)
sce = rbind(sce_2_add , sce[!rownames(sce) %in% genes_dupped , ] )

idx = which(genes_2_simulate$ENSEMBL %in% genes_dupped)
genes_2_simulate$ENSEMBL[idx] = paste0(genes_2_simulate$ENSEMBL[idx] , "_" , genes_2_simulate$celltype[idx])
saveRDS(genes_2_simulate , file = paste0(root.dir , "data/processed/order_analysis_full_ds/simulated_genes_full_ds.Rds"))




```


# Add simulated counts

```{r add-sim-counts, message = FALSE}



add_simulated_counts <- function(sce, celltype, gene, frac_cells_change, range){
  counts = counts(sce)
  current.counts = counts[gene, ]
  idx_2_change = which(sce$type == "chimera" & sce$celltype == celltype)
  idx_2_change = sample(idx_2_change , round(length(idx_2_change)*frac_cells_change))
  current.counts[idx_2_change] = current.counts[idx_2_change] + floor(runif(length(idx_2_change), min=range[1], max=(range[2]+1)))
  counts[gene, ] = current.counts
  counts(sce) = counts
  return(sce)
}

sce_simulated = sce
for (i in 1:nrow(genes_2_simulate)){
  print(i)
  sce_simulated = add_simulated_counts(sce_simulated, celltype = genes_2_simulate$celltype[i], gene = genes_2_simulate$ENSEMBL[i], 
                             range = c(0 , genes_2_simulate$range[i]) , frac_cells_change = genes_2_simulate$frac_2_change[i])
  
}
reducedDim(sce_simulated , "UMAP_scVI") = as.data.frame(uwot::umap(reducedDim(sce_simulated , "scVI") , min_dist = 0.7))
# update logcounts
sce_simulated = scuttle::logNormCounts(sce_simulated)
saveRDS(sce_simulated , file = paste0(root.dir , "data/processed/order_analysis_full_ds/sce_chimera_w_simulations_full_ds.Rds"))


```


# Session Info

```{r sessinf}
sessionInfo()
```
