---
title: "Add scvi embeddings."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(miloDE)
library(miloR)
library(BiocParallel)

ncores = 1
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"

# load sce 
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))


```

# Add scvi

```{r add-scvi, message = FALSE}


add_scvi = function(file){
  current.scvi = read.csv(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/scvi/" , file) , row.names = 1)
  colnames(current.scvi) = paste0("scvi_" , c(1:ncol(current.scvi)))
  
  current.scvi = current.scvi[order(rownames(current.scvi)) , ]
  sce = sce[ , order(colnames(sce))]
  print(mean(colnames(sce) == rownames(current.scvi)))
  
  save.name = str_remove(file , ".csv")
  reducedDim(sce , save.name) = current.scvi
  return(sce)
}


files = list.files(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/scvi/"))
files = files[which(gdata::startsWith(files , "scvi"))]


for (file in files){
  sce = add_scvi(file)
}

reducedDimNames(sce)
saveRDS(sce , paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))



```


# Session Info

```{r sessinf}
sessionInfo()
```
