---
title: "Analysis for simulations."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(miloDE)
library(miloR)
library(ggplot2)
library(ggpubr)
library(viridis)
library(MetBrewer)
library(BiocParallel)
library(tibble)

ncores = 5
mcparam = MulticoreParam(workers = ncores)
register(mcparam)

set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
figures.dir = paste0(root.dir , "figures/detection_analysis/chimera_embryo/")


```


# Get simulated genes and main sce

```{r load-data, message = FALSE}



simulated_genes = readRDS(file = paste0(root.dir , "data/processed/simulations/simulated_genes.Rds"))

anno = expand.grid(order = 2, k = seq(20,30,5), prop = c(0.1), round = c(1:5))

# sort out sub-celltypes
sce = readRDS(paste0(root.dir , "data/processed/simulations/sce_chimera_w_simulations.Rds"))
# add original umaps
sce_original = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera/mouse_embryo_chimera_tal.Rds"))
# subselect
sce_original = sce_original[, sce_original$tal1 == 1]
sce_original = sce_original[, order(colnames(sce_original))]
sce = sce[, order(colnames(sce))]
reducedDim(sce_original , "UMAP_scVI") = reducedDim(sce , "UMAP_scVI")

sub_ct = "Floor plate"


```


# Estimate logFC for each gene - and select 10 of different range


```{r get-data, message = FALSE}


get_de_genes = function(sub_celltype , genes ){
  require(edgeR)
  require(tibble)
  require(scuttle)
  current.sce = sce[, sce$sub_celltype %in% sub_celltype]
  summed = summarizeAssayByGroup(counts(current.sce), colData(current.sce)[,c("sample","type")])
  y <- DGEList(assay(summed, "sum"), samples=colData(summed), lib.size = colSums(assay(summed , "sum")))
  y <- calcNormFactors(y)
  design <- model.matrix(~ factor(type), y$samples)
  y <- estimateDisp(y, design)
  fit <- glmQLFit(y, design, robust=TRUE)
  res <- glmQLFTest(fit, coef=ncol(design))
  out = topTags(res, n = Inf )
  out = as.data.frame(out)
  out = rownames_to_column(out , var = "ENSEMBL")
  out = merge(out , as.data.frame(rowData(sce)))
  out = out[out$ENSEMBL %in% genes , ]
  return(out)
}


bulk_de_stat = get_de_genes(sub_celltype = c("Floor plate") , genes = simulated_genes$ENSEMBL)
bulk_de_stat = bulk_de_stat[ , c("ENSEMBL" , "logFC" , "PValue")]
colnames(bulk_de_stat) = c("ENSEMBL" , "logFC_floorplate" , "PValue_floorplate")
simulated_genes = merge(simulated_genes , bulk_de_stat , all.x = T , all.y = F)


bulk_de_stat = get_de_genes(sub_celltype = c("Floor plate" , "Forebrain" , "Midbrain" , "Hindbrain") , genes = simulated_genes$ENSEMBL)
bulk_de_stat = bulk_de_stat[ , c("ENSEMBL" , "logFC" , "PValue")]
colnames(bulk_de_stat) = c("ENSEMBL" , "logFC_brain" , "PValue_brain")
simulated_genes = merge(simulated_genes , bulk_de_stat , all.x = T , all.y = F)



cols = met.brewer("VanGogh3" , n = 8)[c(3:8)]

# logFC
p = ggplot(simulated_genes , aes(x = factor(range) , y = logFC_floorplate , fill = factor(avg_expr_ct))) + 
  geom_boxplot() +
  theme_bw() + 
  scale_fill_manual(values = cols , name = "Avg Expr") + 
  labs(x = "Max of added range" , y = "logFC")
p
ggsave(filename = paste0(figures.dir, "logFC__vs__pars_sim", ".png"), plot = p, width = 5, height = 3)

# pval
p2 = ggplot(simulated_genes , aes(x = factor(range) , y = -log10(PValue_floorplate) , fill = factor(avg_expr_ct))) + 
  geom_boxplot() +
  theme_bw() + 
  facet_wrap(~frac_2_change) +
  scale_fill_manual(values = cols , name = "Avg Expr") 
p2


 

```

# Add CT putiry stat

```{r add-ct-specificity-stat, message = FALSE}


get_ct_stat_single_milo = function(sce_milo , sub_celltype = "Floor plate"){
  
  nhoods_sce = nhoods(sce_milo)
  
  # celltype specificity per hood
  cells_ct = which(sce_milo$sub_celltype == sub_celltype)
  stat = lapply(1:ncol(nhoods_sce), function(i){
    cells_hood = as.numeric(which(nhoods_sce[,i] == 1))
    out = data.frame(ct_specificity = length(intersect(cells_hood , cells_ct))/length(cells_hood), ct_n_cells = length(intersect(cells_hood , cells_ct)) , 
                     ct_inclusion = length(intersect(cells_hood , cells_ct))/length(cells_ct))
    return(out)
  })
  stat = do.call(rbind , stat)
  stat$Nhood = 1:ncol(nhoods_sce)
  stat$hood_size = colSums(nhoods_sce)
  
  # add average hood size
  stat$avg_hood_size = round( mean(colSums(nhoods_sce)) )
  
  return(stat)
}



stat_ct_specificity = lapply(1:nrow(anno) , function(i){
  sce_milo = readRDS(paste0(root.dir ,  "data/processed/simulations/sce_milo/" ,"sce_order_", anno$order[i] , "_k_" , anno$k[i] , "_round_" , anno$round[i], ".Rds"))
  
  stat_per_ct = get_ct_stat_single_milo(sce_milo)
  stat_per_ct = cbind(stat_per_ct , anno[i, ])
  stat_per_ct$idx = i
  return(stat_per_ct)
})
stat_ct_specificity = do.call(rbind , stat_ct_specificity)


cols = met.brewer("Egypt" , n = 4)[c(1,3,4)]
stat_ct_specificity_to_plot = stat_ct_specificity
stat_ct_specificity_to_plot$k = paste0("k = " , stat_ct_specificity_to_plot$k)
p = ggplot(stat_ct_specificity_to_plot , aes(x = factor(round) , y = ct_specificity , col = factor(k))) + 
  geom_boxplot() + geom_jitter(width = 0.1) +
  facet_wrap(~k , nrow = 3) +
  theme_bw() +
  labs(x = "Replicate" , y = "CT purity") +
  scale_color_manual(values = cols) +
  theme(legend.position = "none") +
  theme(axis.text=element_text(size=15)) +
  theme(legend.text=element_text(size=15) , legend.title = element_text(size=15) ) + 
  theme(text=element_text(size=15) , axis.text.x = element_text(size=13) , axis.text.y = element_text(size=13)) +
  geom_hline(yintercept = .1 , linetype = "dashed") + 
  geom_hline(yintercept = .25 , linetype = "dashed")
p
ggsave(filename = paste0(figures.dir, "k_vs_ct_spec", ".png"), plot = p, width = 3, height = 5)



# add this to milo-de (add gene DE)
milo_de_stat = lapply(1:nrow(anno) , function(i){
  current.milo_de = readRDS(paste0(root.dir ,  "data/processed/simulations/milo_de_selected/" ,"milo_de_order_", anno$order[i] , "_k_" , anno$k[i] , "_round_" , anno$round[i], ".Rds"))
  current.milo_de = merge(current.milo_de , bulk_de_stat , all.x= T , all.y = F)
  current.milo_de = merge(current.milo_de , stat_ct_specificity[, c("k" , "round" , "Nhood" , "ct_specificity" , "ct_n_cells" , "ct_inclusion")] ,
                          by = c("k" , "round" , "Nhood") , all.x= T , all.y = F)
  return(current.milo_de)
})
milo_de_stat = do.call(rbind , milo_de_stat)



```


# Calc stat for each k, ct-spec thresh


```{r calc-stat-for each-data, message = FALSE}


get_detection_stat = function(category , response , response.thresh = 0.1){
  response = response <= response.thresh
  fp = sum(category == 0 & response == 1)
  fn = sum(category == 1 & response == 0)
  tp = sum(category == 1 & response == 1)
  tn = sum(category == 0 & response == 0)
  sensitivity = tp/(tp + fn)
  specificity = tn/(tn + fp)
  fdr = fp/(fp + tp)
  fomr = fn/(fn + tn)
  out = data.frame(sensitivity = sensitivity , specificity = specificity , fdr = fdr , fomr = fomr)
  return(out)
}

# selected genes with wide range of logFC
genes = simulated_genes$ENSEMBL[simulated_genes$SYMBOL %in% c("Vipas39" , "Pomt1" , "Dnajc10" , "Med27" , "Rngtt" , 
                                                              "Fbln2" , "Abcf3" , "Zfp110" , "Hdhd5" , "Gabpa")]

anno_extended = expand.grid(k = c(20,25,30), round = c(1:5) , ct_specificity.thresh = c(0, 0.1 , 0.25) , ENSEMBL = genes)


stat = lapply(1:nrow(anno_extended) , function(i){
  k = anno_extended$k[i]
  round = anno_extended$round[i]
  ct_specificity.thresh = anno_extended$ct_specificity.thresh[i]
  ENSEMBL = anno_extended$ENSEMBL[i]
  
  current.milo_de = milo_de_stat[milo_de_stat$ENSEMBL == ENSEMBL & milo_de_stat$k == k & milo_de_stat$round == round , ]
  current.milo_de$pval_corrected_across_nhoods[is.na(current.milo_de$pval_corrected_across_nhoods)] = 1
  category = current.milo_de$ct_specificity > ct_specificity.thresh
  response = current.milo_de$pval_corrected_across_nhoods
  out = get_detection_stat(category , response , response.thresh = 0.1)
  return(out)
})
stat = do.call(rbind , stat)
stat = cbind(stat , anno_extended)
stat = merge(stat , simulated_genes , all.x = T , all.y = F)
stat$logFC_floorplate = round(stat$logFC_floorplate , 2)
stat$logFC_brain = round(stat$logFC_brain , 3)
stat = merge(stat , simulated_genes[, c("ENSEMBL" , "SYMBOL")] , all.x = T , all.y = F)
stat$ct_specificity.thresh = paste0("CT purity\nthreshold = ", stat$ct_specificity.thresh)


```

# Plot boxplots sensitivity-FDR

## Short version

```{r plot, message = FALSE}


# focus on 5 genes instead of 10 to not overwhelm plotting
stat_reduced = stat[stat$logFC_floorplate %in% c(1.17 , 2.04 , 2.76 , 3.6 , 4.19) , ]

p1 = ggplot(stat_reduced , aes(x = factor(logFC_floorplate) , y = sensitivity , color = factor(k))) +
  geom_boxplot() + 
  theme_bw() + 
  facet_wrap(~ct_specificity.thresh , ncol = 4 ) + 
  scale_color_manual(values = cols, name = "k") + 
  ylim(c(0,1)) + 
  labs(x = "Estimated logFC" , y = "Sensitivity") +
  theme(axis.text=element_text(size=17)) +
  theme(legend.text=element_text(size=17) , legend.title = element_text(size=17) ) + 
  theme(text=element_text(size=17) , axis.text.x = element_text(size=13) , axis.text.y = element_text(size=13))  + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p2 = ggplot(stat_reduced , aes(x = factor(logFC_floorplate) , y = fdr , color = factor(k))) +
  geom_boxplot() + 
  theme_bw() + 
  facet_wrap(~ct_specificity.thresh , ncol = 4 ) + 
  scale_color_manual(values = cols, name = "k") + 
  ylim(c(0,1)) + 
  labs(x = "Estimated logFC" , y = "FDR") +
  theme(axis.text=element_text(size=17)) +
  theme(legend.text=element_text(size=17) , legend.title = element_text(size=17) ) + 
  theme(text=element_text(size=17) , axis.text.x = element_text(size=13) , axis.text.y = element_text(size=13))  + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p = ggarrange(p1,p2, nrow = 2 , common.legend = T , legend = "right") 
p
ggsave(filename = paste0(figures.dir, "performance__all", ".png"), plot = p, width = 9, height = 5)



```

## Extended version

```{r plot, message = FALSE}


# focus on 5 genes instead of 10 to not overwhelm plotting
stat_reduced = stat
stat_reduced$de_bulk_bool = stat_reduced$PValue_brain < 0.05

cols_fill = c("papayawhip" , "peachpuff3")
  
p1 = ggplot(stat_reduced , aes(x = factor(logFC_floorplate) , y = sensitivity , fill = de_bulk_bool , color = factor(k))) +
  geom_boxplot() + 
  theme_bw() + 
  facet_wrap(~ct_specificity.thresh , ncol = 4 ) + 
  scale_color_manual(values = cols, name = "k") + 
  scale_fill_manual(values = cols_fill) + 
  ylim(c(0,1)) + 
  labs(x = "Estimated logFC" , y = "Sensitivity") +
  theme(axis.text=element_text(size=17)) +
  theme(legend.text=element_text(size=17) , legend.title = element_text(size=17) ) + 
  theme(text=element_text(size=17) , axis.text.x = element_text(size=13) , axis.text.y = element_text(size=13))  + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p2 = ggplot(stat_reduced , aes(x = factor(logFC_floorplate) , y = fdr , fill = de_bulk_bool , color = factor(k))) +
  geom_boxplot() + 
  theme_bw() + 
  facet_wrap(~ct_specificity.thresh , ncol = 4 ) + 
  scale_color_manual(values = cols, name = "k") + 
  scale_fill_manual(values = cols_fill) + 
  ylim(c(0,1)) + 
  labs(x = "Estimated logFC" , y = "FDR") +
  theme(axis.text=element_text(size=17)) +
  theme(legend.text=element_text(size=17) , legend.title = element_text(size=17) ) + 
  theme(text=element_text(size=17) , axis.text.x = element_text(size=13) , axis.text.y = element_text(size=13))  + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p = ggarrange(p1,p2, nrow = 2 , common.legend = T , legend = "right") 
p
ggsave(filename = paste0(figures.dir, "performance__all__extended", ".png"), plot = p, width = 9, height = 5)



```



# Session Info

```{r sessinf}
sessionInfo()
```
