---
title: "This pipeline to get DA statistic for DA-DE analysis"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}

library(SingleCellExperiment)
library(BiocParallel)
library(geneBasisR)
library(splatter)
library(scran)
library(miloR)
library(miloDE)
library(stringr)
library(dplyr)

ncores = 30
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"
source(paste0(root.dir , "miloDE_analysis/core_functions.R"))


sims = readRDS(file = paste0(root.dir , "data/processed/da_de/simulations_splatter/sims.Rds"))


anno_1 = expand.grid(order = 1 , k = c(75,150,250) , seed = c(13,17,32,48,56))
anno_2 = expand.grid(order = 2 , k = c(15,25,35) , seed = c(13,17,32,48,56))
anno = rbind(anno_1 , anno_2)


```

# Get milo DE stat

```{r milo-de-stat, message = FALSE}


get_milo_stat = function(sce_milo , reducedDim_name , pval.thresh = 0.1){
  
  de_stat = miloDE::de_test_neighbourhoods(sce_milo , design = ~factor(Group) , covariates = c("sample" , "Group") , min_n_cells_per_sample = 1, min_count = 0 , verbose = F)
  colnames(de_stat)[colnames(de_stat) == "gene"] = "Gene"
  rowdata = as.data.frame(rowData(sce_milo))
  de_stat = merge(de_stat , rowdata[, c("Gene" , "DEFacGroup2")] , all.x = T , all.y = F)
  # get combined stat per Nhood
  stat = as.data.frame(de_stat %>% group_by(Nhood) %>% dplyr::summarise(
    tp = sum(pval_corrected_across_genes <= pval.thresh & DEFacGroup2 != 1) ,
    fp = sum(pval_corrected_across_genes <= pval.thresh & DEFacGroup2 == 1) , 
    tn = sum(pval_corrected_across_genes > pval.thresh & DEFacGroup2 == 1) , 
    fn = sum(pval_corrected_across_genes > pval.thresh & DEFacGroup2 != 1)
  ))
  stat$frac_DE = (stat$tp + stat$fp)/(stat$tp + stat$fp + stat$tn + stat$fn)
  stat$n_DE = stat$tp + stat$fp
  stat$reducedDim_name = reducedDim_name
  return(stat)
}


stat = bplapply(1:length(sims) , function(j){
  sim = sims[[j]]
  stat_per_sim = lapply(1:nrow(anno) , function(i){
    set.seed(anno$seed[i])
    out_all = miloDE::assign_neighbourhoods(sim , reducedDim_name = "pca.all" , order = anno$order[i] , k = anno$k[i] , d = 5 , verbose = F , filtering = T)
    out_all = get_milo_stat(out_all , "pca.all")
    
    set.seed(anno$seed[i])
    out_not_de = miloDE::assign_neighbourhoods(sim , reducedDim_name = "pca.not_de" , order = anno$order[i] , k = anno$k[i] , d = 5 , verbose = F , filtering = T)
    out_not_de = get_milo_stat(out_not_de , "pca.not_de")
    
    out = rbind(out_all , out_not_de)
    out = cbind(out , anno[i , ])
    
    return(out)
  })
  stat_per_sim = do.call(rbind , stat_per_sim)
  
  id = names(sims)[j]
  id = stringr::str_split(id , "_")
  id = id[[1]]
  stat_per_sim$batch_effect = as.logical(id[1])
  stat_per_sim$de_prob = as.numeric(id[2])
  stat_per_sim$de_facLoc = as.numeric(id[3])
  stat_per_sim$round_sim = as.numeric(id[4])
  
  return(stat_per_sim)
} , BPPARAM = mcparam)
stat = do.call(rbind , stat)
saveRDS(stat , file = paste0(root.dir , "data/processed/da_de/simulations_splatter/stat_de.Rds"))



```


# Session Info

```{r sessinf}
sessionInfo()
```
