---
title: "Assign neighbourhoods and miloDE for different embeddings."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(miloDE)
library(miloR)
library(BiocParallel)
library(MouseGastrulationData)
library(scran)
library(stringr)

ncores = 15
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
set.seed(32)

root.dir = "/nfs/research/marioni/alsu/hubmap_metaRef/"

# load sce 
sce = readRDS(paste0(root.dir , "data/sces/mouse_embryo/chimera_WT/mouse_embryo_wt_chimera.Rds"))
rowdata = as.data.frame(rowData(sce))

```


# Assign neighbourhoods

We will not be saving this output since it is fairly easy to regenerate and saving it will occupy a lot of memory

```{r assign-nhoods, message = FALSE}


anno = expand.grid(reduced_dim = reducedDimNames(sce) , order = 1 , k = 100 , round = c(1:5))
anno$id = paste0(anno$reduced_dim , "_" , anno$order , "_" , anno$k , "_" , anno$round)


sce_milo = lapply(1:nrow(anno) , function(i){
 set.seed(anno$seed[i])
 current.sce = miloDE::assign_neighbourhoods(sce , reducedDim_name = as.character(anno$reduced_dim[i]) , k = anno$k[i], prop = 0.1 , order = anno$order[i], filtering = T)
 return(current.sce)
})
names(sce_milo) = anno$id
#saveRDS(sce_milo , file = paste0(root.dir , "data/processed/embedding_analysis_updated/sce_milo.Rds"))


```

# DE stat

```{r de-stat, message = FALSE}



de_stat = lapply(1:length(sce_milo) , function(i){
  proc.file = paste0(root.dir , "data/processed/embedding_analysis_updated/proc/", names(sce_milo)[i] ,".Rds")
  if (!file.exists(proc.file)){
    dummy = 1
    saveRDS(dummy , paste0(root.dir , "data/processed/embedding_analysis_updated/proc/", names(sce_milo)[i] ,".Rds"))
    out = miloDE::de_test_neighbourhoods(sce_milo[[i]] , design = ~type , covariates = c("type") , min_n_cells_per_sample = 1 , BPPARAM = mcparam , output_type = "data.frame" , verbose = FALSE)
    id = names(sce_milo)[i]
    out$id = id
    id = str_split(id , pattern = "_")
    id = id[[1]]
    out$reduced_dim_method = id[1]
    out$reduced_dim_type = id[2]
    out$reduced_dim_genes = id[3]
    out$reduced_dim = paste0(id[1] , "_" , id[2] , "_" , id[3])
    out$order = as.numeric(id[4])
    out$k = as.numeric(id[5])
    out$round = as.numeric(id[6])
    saveRDS(out , file = paste0(root.dir , "data/processed/embedding_analysis_updated/milo_de/", names(sce_milo)[i] ,".Rds"))
    return(out)
  } else {
    return(NULL)
  }
})


```

## Combine some selected stat separately

```{r de-stat-sel, message = FALSE}


chimera_speicific_genes = c("Rpgrip1" , "Slc24a5" , "Actb", "Cbx3" , "Myef2" , "Pfas" , "Ssr1" , "Klhl9" , "Marcks" , "Dpysl2" , "Gnb1" , "Ankrd11")
genes = rowdata$ENSEMBL[rowdata$SYMBOL %in% chimera_speicific_genes]

de_stat = bplapply(list.files(paste0(root.dir , "data/processed/embedding_analysis_updated/milo_de/")) , function(file){
  print(file)
  out = readRDS(paste0(root.dir , "data/processed/embedding_analysis_updated/milo_de/" , file))
  out = out[out$gene %in% genes , ]
  return(out)
} , BPPARAM = mcparam)
de_stat = do.call(rbind , de_stat)
saveRDS(de_stat , paste0(root.dir , "data/processed/embedding_analysis_updated/milo_de_chimera_genes.Rds"))


```

# Session Info

```{r sessinf}
sessionInfo()
```
